// ═══════════════════════════════════════════════════════════════
// bibliography-data.js — Bibliographie DFIR de référence
// Page : references/bibliography.html
//
// Sélection de ~70 ressources indispensables pour un enquêteur
// numérique francophone, organisées par domaine. Mix livres,
// standards, rapports, articles fondateurs, blogs et podcasts.
//
// Critères : autorité de l'auteur, actualité du contenu, pertinence
// au contexte suisse / européen, facilité d'accès pour un étudiant
// CAS Investigation Numérique.
// ═══════════════════════════════════════════════════════════════
window.REF_CONFIG = {

  pageId:    'bibliography',
  emoji:     '📖',
  title:     'Bibliographie DFIR',
  subtitle:  'Livres · Standards · Rapports · Articles · Blogs · Podcasts',
  description: "Sélection de références indispensables pour pratiquer et enseigner l'investigation numérique forensique. Filtrable par domaine, format, niveau, langue. Liens vers les sources officielles quand elles sont publiques.",

  filters: [
    { id: 'category', label: 'Domaine',   kind: 'select', autoOptions: true },
    { id: 'format',   label: 'Format',    kind: 'select', autoOptions: true },
    { id: 'language', label: 'Langue',    kind: 'select', autoOptions: true },
    { id: 'level',    label: 'Niveau',    kind: 'select', autoOptions: true },
    { id: 'q',        label: 'Recherche', kind: 'text',   placeholder: 'ex: Volatility, RGPD, deepfake, Akira…' }
  ],

  columns: [
    { id: 'format',   label: 'Format',  kind: 'badge', sortable: true,
      badgeMap: {
        'Livre':      'cyan',
        'Standard':   'gold',
        'Rapport':    'orange',
        'Article':    'purple',
        'Blog':       'green',
        'Podcast':    'red',
        'Conférence': 'blue',
        'Loi':        'red',
        'Cours':      'purple'
      } },
    { id: 'title',    label: 'Titre',    kind: 'bold',  sortable: true },
    { id: 'authors',  label: 'Auteur·s', kind: 'plain', sortable: true },
    { id: 'year',     label: 'Année',    kind: 'mono',  sortable: true },
    { id: 'category', label: 'Domaine',  kind: 'tag',   sortable: true }
  ],

  detail: {
    titleField: 'title',
    callout: d => d.warning ? { tone: 'gold', html: `<b>⚠</b> ${d.warning}` } : null,
    grid: [
      { label: 'Auteur·s', field: 'authors' },
      { label: 'Éditeur',  field: 'editor' },
      { label: 'Année',    field: 'year' },
      { label: 'Format',   field: 'format' },
      { label: 'Langue',   field: 'language' },
      { label: 'Niveau',   field: 'level' },
      { label: 'Lien',     render: d => d.url ? `<a href="${d.url}" target="_blank" rel="noopener" style="color:var(--cyan)">${d.url.replace(/^https?:\/\//,'').slice(0,55)}…</a>` : '<span class="ref-dim">—</span>' }
    ],
    description: 'description',
    notes: 'notes',
    sections: [
      { label: 'Mots-clés', field: 'tags', kind: 'list' }
    ]
  },

  search: {
    fields: ['title', 'authors', 'description', 'notes', 'tags', 'editor']
  },

  data: [
    // ═══════════════════════ FORENSIQUE GÉNÉRALE ═══════════════════════
    {
      id: 'carrier-fs-forensic',
      title: 'File System Forensic Analysis',
      authors: 'Brian Carrier',
      editor: 'Addison-Wesley',
      year: 2005,
      category: 'Forensique générale',
      language: 'en',
      level: 'avancé',
      format: 'Livre',
      url: 'https://www.digital-evidence.org/',
      tags: ['FAT', 'NTFS', 'ext', 'HFS+', 'data carving', 'TSK', 'Sleuthkit'],
      description: "La référence absolue sur la forensique des systèmes de fichiers (FAT, NTFS, Ext2/3, HFS+). Brian Carrier est aussi le créateur de The Sleuth Kit et Autopsy. Couverture exhaustive bas niveau : MFT, journaling, slack space, unallocated.",
      notes: "Un peu ancien sur les nouveautés (APFS, exFAT moderne), mais les concepts fondamentaux n'ont pas bougé. À lire en parallèle de la doc Sleuthkit officielle pour les implémentations actuelles."
    },
    {
      id: 'casey-digital-evidence',
      title: 'Digital Evidence and Computer Crime',
      authors: 'Eoghan Casey',
      editor: 'Academic Press / Elsevier',
      year: 2011,
      category: 'Forensique générale',
      language: 'en',
      level: 'intermédiaire',
      format: 'Livre',
      tags: ['méthodologie', 'preuve', 'investigation', 'cybercrime'],
      description: "Manuel classique de l'investigation numérique, 3e édition. Couvre méthodologie, droit, technique. Eoghan Casey est éditeur en chef de la revue Digital Investigation (Elsevier).",
      notes: "Bon livre d'introduction généraliste, surtout pour les aspects méthodologiques et judiciaires. À compléter par des références techniques plus à jour."
    },
    {
      id: 'altheide-carvey-osource',
      title: 'Digital Forensics with Open Source Tools',
      authors: 'Cory Altheide, Harlan Carvey',
      editor: 'Syngress',
      year: 2011,
      category: 'Forensique générale',
      language: 'en',
      level: 'intermédiaire',
      format: 'Livre',
      tags: ['open source', 'Linux', 'Sleuthkit', 'Volatility'],
      description: "Couvre l'ensemble du workflow DFIR avec uniquement des outils open-source : acquisition (dd, dcfldd), analyse FS (TSK), mémoire (Volatility), réseau (Wireshark), mobile.",
      notes: "Excellent point de départ pour qui veut bâtir un atelier DFIR sans licences propriétaires. Plusieurs outils ont évolué — vérifier les versions actuelles."
    },
    {
      id: 'nelson-phillips-steuart',
      title: 'Guide to Computer Forensics and Investigations',
      authors: 'Bill Nelson, Amelia Phillips, Christopher Steuart',
      editor: 'Cengage Learning',
      year: 2019,
      category: 'Forensique générale',
      language: 'en',
      level: 'intro',
      format: 'Livre',
      tags: ['manuel', 'cours', 'examen', 'CCFE', 'CFE'],
      description: "Manuel universitaire classique (6e édition), très utilisé en formations DFIR aux USA. Couvre l'ensemble du cycle : preuve, chaîne de possession, outils, rapport, témoignage.",
      notes: "Bon manuel pour démarrer si on veut une approche très pédagogique pas-à-pas. Orientation US (procédures, lois) — adapter pour le contexte CH/EU."
    },

    // ═══════════════════════ WINDOWS FORENSICS ═══════════════════════
    {
      id: 'carvey-windows-toolkit',
      title: 'Windows Forensic Analysis Toolkit (4th edition)',
      authors: 'Harlan Carvey',
      editor: 'Syngress',
      year: 2014,
      category: 'Windows forensics',
      language: 'en',
      level: 'avancé',
      format: 'Livre',
      tags: ['registre', 'Windows', 'RegRipper', 'artefacts'],
      description: "Référence sur les artefacts Windows par l'auteur de RegRipper. Plongée profonde dans le registre, les journaux d'événements, les Shadow Copies, les artefacts de programme.",
      notes: "Couplé à la 5e édition partielle en ligne (Investigating Windows Systems, 2018). Pour les versions Windows post-10, suivre aussi le blog de l'auteur (windowsir.blogspot.com)."
    },
    {
      id: 'carvey-investigating-win',
      title: 'Investigating Windows Systems',
      authors: 'Harlan Carvey',
      editor: 'Academic Press',
      year: 2018,
      category: 'Windows forensics',
      language: 'en',
      level: 'avancé',
      format: 'Livre',
      tags: ['cas pratiques', 'Windows 10', 'analyse'],
      description: "Suite logique du WFA Toolkit, orientée études de cas. Walk-throughs d'incidents réels : ransomware, intrusion, exfiltration, sur des images Windows 7-10.",
      notes: "Format moins exhaustif mais plus opérationnel que WFA. Idéal pour qui sait déjà les bases et veut voir 'comment on enquête vraiment'."
    },
    {
      id: 'zimmerman-tools',
      title: 'Eric Zimmerman Tools (suite forensique)',
      authors: 'Eric Zimmerman',
      editor: 'GitHub / Kroll',
      year: 2024,
      category: 'Windows forensics',
      language: 'en',
      level: 'intermédiaire',
      format: 'Cours',
      url: 'https://ericzimmerman.github.io/',
      tags: ['EZ tools', 'AmcacheParser', 'MFTECmd', 'PECmd', 'KAPE'],
      description: "Suite d'outils gratuits incontournable pour la forensique Windows : MFTECmd (MFT), Amcache, AppCompat, Prefetch, Shellbags, JLECmd (Jump Lists), KAPE (acquisition rapide). Tous open-source.",
      notes: "Documentation en ligne + canal Discord actif. Combiner avec Timeline Explorer (autre outil EZ) pour la corrélation chronologique."
    },
    {
      id: '13cubed-youtube',
      title: '13Cubed (chaîne YouTube)',
      authors: 'Richard Davis',
      editor: 'YouTube',
      year: 2024,
      category: 'Windows forensics',
      language: 'en',
      level: 'intermédiaire',
      format: 'Cours',
      url: 'https://www.youtube.com/@13Cubed',
      tags: ['tutoriel', 'vidéo', 'Windows', 'CTF'],
      description: "Tutoriels vidéo très pédagogiques sur les artefacts Windows : Shellbags, ShimCache, Amcache, événements de connexion, persistence. Format court (10-30 min), captures écran, démos.",
      notes: "Excellent pour apprendre visuellement. Ressource gratuite la plus utile pour démarrer concrètement la forensique Windows."
    },

    // ═══════════════════════ macOS FORENSICS ═══════════════════════
    {
      id: 'edwards-mac',
      title: 'mac4n6 (blog & SANS FOR518)',
      authors: 'Sarah Edwards',
      editor: 'SANS / Independent',
      year: 2024,
      category: 'macOS forensics',
      language: 'en',
      level: 'avancé',
      format: 'Blog',
      url: 'https://www.mac4n6.com/',
      tags: ['macOS', 'APFS', 'unified logs', 'KnowledgeC'],
      description: "Référence mondiale sur la forensique macOS. Auteure du cours SANS FOR518. Blog actif sur les artefacts macOS (Unified Logs, KnowledgeC.db, biome, CryptoTokenKit, persistance).",
      notes: "Le poster SANS macOS Forensics est gratuit et indispensable. Ses scripts (APOLLO, mac_apt) couvrent ce que les outils commerciaux ne décodent pas encore."
    },
    {
      id: 'bradley-sherlocked',
      title: 'The Mac Hacker\'s Handbook / Sherlocked',
      authors: 'Jaron Bradley',
      editor: 'Independent / 0xDEADBEEF',
      year: 2020,
      category: 'macOS forensics',
      language: 'en',
      level: 'avancé',
      format: 'Livre',
      tags: ['malware macOS', 'persistance', 'reverse'],
      description: "Sherlocked: Investigating macOS Malware — couvre les techniques de persistance macOS modernes, l'analyse de malware natif, les TCC (Transparency, Consent, Control).",
      notes: "Important pour qui investigue des compromissions de postes Apple en entreprise. Très technique."
    },

    // ═══════════════════════ LINUX FORENSICS ═══════════════════════
    {
      id: 'polstra-linux',
      title: 'Linux Forensics',
      authors: 'Philip Polstra',
      editor: 'Pentester Academy / Indep.',
      year: 2015,
      category: 'Linux forensics',
      language: 'en',
      level: 'intermédiaire',
      format: 'Livre',
      tags: ['Linux', 'ext4', 'journalctl', 'auditd'],
      description: "Forensique pratique des serveurs Linux : ext4, journaux systemd, auditd, /proc, persistance (cron, systemd timers, .bashrc). Approche live + post-mortem.",
      notes: "Adapté à la majorité des cas serveur (Debian/Ubuntu/RHEL). Pour les conteneurs et K8s, compléter par les rapports d'Aqua Security / Sysdig."
    },
    {
      id: 'pomeranz-sans',
      title: 'SANS FOR577: LINUX Incident Response & Threat Hunting',
      authors: 'Hal Pomeranz',
      editor: 'SANS',
      year: 2023,
      category: 'Linux forensics',
      language: 'en',
      level: 'avancé',
      format: 'Cours',
      url: 'https://www.sans.org/cyber-security-courses/linux-incident-response-threat-hunting/',
      tags: ['Linux IR', 'SANS', 'threat hunting'],
      description: "Cours SANS dédié à la réponse incident Linux. Hal Pomeranz est l'une des références mondiales. Couvre live response, triage, persistance, malware Linux.",
      notes: "Cher (~10k CHF). Le poster Linux Cheatsheet associé est gratuit et précieux. Articles connexes sur sansforensics.wordpress.com."
    },

    // ═══════════════════════ MOBILE FORENSICS ═══════════════════════
    {
      id: 'mahalik-mobile',
      title: 'Practical Mobile Forensics (4th edition)',
      authors: 'Heather Mahalik, Rohit Tamma, Satish Bommisetty',
      editor: 'Packt',
      year: 2020,
      category: 'Mobile forensics',
      language: 'en',
      level: 'intermédiaire',
      format: 'Livre',
      tags: ['iOS', 'Android', 'Cellebrite', 'Magnet AXIOM'],
      description: "Manuel de référence sur la forensique mobile. iOS (acquisition, iTunes backups, KnowledgeC), Android (ADB, root, dump physique). Heather Mahalik dirige le SANS FOR585.",
      notes: "Couvre les outils propriétaires (Cellebrite UFED, AXIOM) ET open-source. Indispensable pour qui investigue des smartphones professionnellement."
    },
    {
      id: 'brignoni-leapp',
      title: 'Initialization Vectors blog + ALEAPP/iLEAPP',
      authors: 'Alexis Brignoni',
      editor: 'GitHub / abrignoni.com',
      year: 2024,
      category: 'Mobile forensics',
      language: 'en',
      level: 'avancé',
      format: 'Blog',
      url: 'https://abrignoni.blogspot.com/',
      tags: ['ALEAPP', 'iLEAPP', 'RLEAPP', 'open source'],
      description: "Auteur des outils ALEAPP (Android), iLEAPP (iOS), RLEAPP (cloud), VLEAPP (vehicle). Outils Python open-source largement adoptés en DFIR mobile. Blog très technique sur l'analyse d'artefacts mobiles obscurs.",
      notes: "Communauté active sur GitHub. Plugins ajoutés régulièrement pour les apps grand public (WhatsApp, Signal, TikTok, Instagram, etc.)."
    },
    {
      id: 'sans-for585',
      title: 'SANS FOR585: Smartphone Forensic Analysis In-Depth',
      authors: 'Heather Mahalik, Domenica Crognale',
      editor: 'SANS',
      year: 2024,
      category: 'Mobile forensics',
      language: 'en',
      level: 'avancé',
      format: 'Cours',
      url: 'https://www.sans.org/cyber-security-courses/smartphone-forensic-analysis-in-depth/',
      tags: ['SANS', 'iOS', 'Android', 'certification GASF'],
      description: "Le cours de référence mondial en forensique smartphone. Couvre tous les modèles, contournements de verrouillage (avec considérations légales), apps de messagerie chiffrée.",
      notes: "Certification associée : GASF. Poster Smartphone Forensics gratuit téléchargeable."
    },

    // ═══════════════════════ MEMORY FORENSICS ═══════════════════════
    {
      id: 'ligh-art-memory',
      title: 'The Art of Memory Forensics',
      authors: 'Michael Hale Ligh, Andrew Case, Jamie Levy, Aaron Walters',
      editor: 'Wiley',
      year: 2014,
      category: 'Memory forensics',
      language: 'en',
      level: 'avancé',
      format: 'Livre',
      url: 'https://www.memoryanalysis.net/amf',
      tags: ['Volatility', 'RAM', 'rootkit', 'kernel'],
      description: "LA référence absolue sur la forensique mémoire. Auteurs = équipe Volatility. Couvre Windows, Linux, macOS. Plugin development. Détection de malware en RAM (rootkits, code injection, hidden processes).",
      notes: "Édition 2014 — la base théorique est intacte mais les plugins ont migré vers Volatility 3. Combiner avec la doc volatility3.readthedocs.io et le blog Volexity."
    },
    {
      id: 'volatility3-docs',
      title: 'Volatility 3 Documentation',
      authors: 'Volatility Foundation',
      editor: 'GitHub / volatilityfoundation.org',
      year: 2024,
      category: 'Memory forensics',
      language: 'en',
      level: 'avancé',
      format: 'Standard',
      url: 'https://volatility3.readthedocs.io/',
      tags: ['Volatility', 'plugins', 'ISF'],
      description: "Documentation officielle de Volatility 3, le framework de référence pour l'analyse mémoire. Plugins, profils, symboles ISF, écriture de plugins custom.",
      notes: "Volatility 3 ≠ Volatility 2 — syntaxe différente, certains plugins encore en cours de migration. Voir aussi le blog volatility-labs.blogspot.com."
    },
    {
      id: 'volexity-blog',
      title: 'Volexity Threat Research',
      authors: 'Andrew Case et al.',
      editor: 'Volexity Inc.',
      year: 2024,
      category: 'Memory forensics',
      language: 'en',
      level: 'avancé',
      format: 'Blog',
      url: 'https://www.volexity.com/blog/',
      tags: ['APT', 'memory analysis', 'Triangulation', 'zero-day'],
      description: "Blog technique de Volexity : recherches actives sur APT (Operation Triangulation iOS découvert ici), zéro-days, analyse mémoire d'incidents réels. Niveau très avancé.",
      notes: "Posts irréguliers mais à chaque fois techniquement remarquables. Indispensable pour rester à jour sur les techniques de mémoire."
    },

    // ═══════════════════════ NETWORK FORENSICS ═══════════════════════
    {
      id: 'davidoff-ham-net',
      title: 'Network Forensics: Tracking Hackers Through Cyberspace',
      authors: 'Sherri Davidoff, Jonathan Ham',
      editor: 'Prentice Hall',
      year: 2012,
      category: 'Network forensics',
      language: 'en',
      level: 'intermédiaire',
      format: 'Livre',
      tags: ['NetFlow', 'pcap', 'NIDS', 'logs réseau'],
      description: "Manuel de référence sur la forensique réseau : capture, NetFlow, analyse pcap, NIDS, attribution. Très progressif, beaucoup d'exemples concrets.",
      notes: "Quelques outils datés mais les concepts (volatilité réseau, ordre de capture, attribution par TTPs) restent valides."
    },
    {
      id: 'sanders-wireshark',
      title: 'Practical Packet Analysis (3rd edition)',
      authors: 'Chris Sanders',
      editor: 'No Starch Press',
      year: 2017,
      category: 'Network forensics',
      language: 'en',
      level: 'intro',
      format: 'Livre',
      tags: ['Wireshark', 'pcap', 'TCP/IP', 'sniffing'],
      description: "Le livre Wireshark de référence. Couverture progressive de TCP/IP, capture, filtres, dissectors. Très clair pour débuter l'analyse réseau forensique.",
      notes: "Auteur aussi de 'Applied Network Security Monitoring' (No Starch 2013) — complémentaire pour le SOC."
    },
    {
      id: 'bejtlich-nsm',
      title: 'The Practice of Network Security Monitoring',
      authors: 'Richard Bejtlich',
      editor: 'No Starch Press',
      year: 2013,
      category: 'Network forensics',
      language: 'en',
      level: 'intermédiaire',
      format: 'Livre',
      tags: ['NSM', 'Security Onion', 'détection', 'SIEM'],
      description: "Doctrine NSM (Network Security Monitoring) : surveiller en continu pour détecter avant l'impact. Architecture, outils (Security Onion, Bro/Zeek, Snort), workflow analyste.",
      notes: "Bejtlich a popularisé NSM. Sa doctrine est devenue standard dans les SOC modernes (couplée à EDR)."
    },

    // ═══════════════════════ MALWARE / REVERSE / THREAT INTEL ═══════════════════════
    {
      id: 'sikorski-honig-malware',
      title: 'Practical Malware Analysis',
      authors: 'Michael Sikorski, Andrew Honig',
      editor: 'No Starch Press',
      year: 2012,
      category: 'Malware / Reverse',
      language: 'en',
      level: 'avancé',
      format: 'Livre',
      tags: ['IDA Pro', 'reverse', 'malware', 'sandbox'],
      description: "RÉFÉRENCE en analyse de malware. IDA Pro, OllyDbg, sandbox, anti-debug, packers, rootkits. Labs pratiques téléchargeables.",
      notes: "Le livre reste excellent malgré son âge — les fondamentaux du reverse n'ont pas changé. Pour les techniques modernes (LLM-assisted reverse), suivre les conférences."
    },
    {
      id: 'dang-gazet-reverse',
      title: 'Practical Reverse Engineering',
      authors: 'Bruce Dang, Alexandre Gazet, Elias Bachaalany',
      editor: 'Wiley',
      year: 2014,
      category: 'Malware / Reverse',
      language: 'en',
      level: 'avancé',
      format: 'Livre',
      tags: ['x86', 'x64', 'ARM', 'kernel', 'rootkit'],
      description: "Reverse engineering systémique : x86/x64, ARM, kernel Windows, rootkits. Niveau exigeant.",
      notes: "Compléter avec 'Rootkits: Subverting the Windows Kernel' (Hoglund & Butler) pour le côté offensif Windows."
    },
    {
      id: 'monnappa-malware',
      title: 'Learning Malware Analysis',
      authors: 'Monnappa K A',
      editor: 'Packt',
      year: 2018,
      category: 'Malware / Reverse',
      language: 'en',
      level: 'intermédiaire',
      format: 'Livre',
      tags: ['malware', 'reverse', 'Windows'],
      description: "Approche plus progressive que Sikorski/Honig. Auteur reconnu (FireEye / créateur de Limon sandbox). Bonnes explications pédagogiques.",
      notes: "Bon livre 'pont' entre Practical Malware Analysis (assez exigeant) et la pratique quotidienne SOC/IR."
    },
    {
      id: 'mitre-attack',
      title: 'MITRE ATT&CK Framework',
      authors: 'MITRE Corporation',
      editor: 'attack.mitre.org',
      year: 2024,
      category: 'Malware / Reverse',
      language: 'en',
      level: 'référence',
      format: 'Standard',
      url: 'https://attack.mitre.org/',
      tags: ['MITRE', 'TTP', 'tactiques', 'techniques', 'attribution'],
      description: "Référentiel mondial des tactiques, techniques et procédures (TTPs) utilisées par les attaquants. 14 tactiques × ~200 techniques. Base de tous les SOC, EDR, threat intelligence reports modernes.",
      notes: "Mis à jour régulièrement. Voir aussi ATT&CK for ICS, ATT&CK for Cloud. Cartographie indispensable pour les rapports d'incident."
    },
    {
      id: 'diamond-model',
      title: 'The Diamond Model of Intrusion Analysis',
      authors: 'Sergio Caltagirone, Andrew Pendergast, Christopher Betz',
      editor: 'Center for Cyber Intelligence Analysis',
      year: 2013,
      category: 'Malware / Reverse',
      language: 'en',
      level: 'avancé',
      format: 'Article',
      url: 'https://www.activeresponse.org/wp-content/uploads/2013/07/diamond.pdf',
      tags: ['threat intelligence', 'attribution', 'model'],
      description: "Modèle de référence pour l'analyse structurée d'intrusion : Adversary, Capability, Infrastructure, Victim — reliés par 4 features (Methodology, Resources, Timestamp, Direction).",
      notes: "Complémentaire à Kill Chain (Lockheed Martin) et MITRE ATT&CK. Utilisé pour structurer les rapports d'attribution sérieux."
    },
    {
      id: 'mandiant-mtrends',
      title: 'M-Trends Annual Report',
      authors: 'Mandiant (Google Cloud)',
      editor: 'cloud.google.com/security/resources',
      year: 2025,
      category: 'Malware / Reverse',
      language: 'en',
      level: 'référence',
      format: 'Rapport',
      url: 'https://cloud.google.com/security/resources/m-trends',
      tags: ['threat intelligence', 'APT', 'dwell time', 'rapport'],
      description: "Rapport annuel Mandiant sur les tendances d'intrusion vues côté IR : dwell time, vecteurs initiaux, groupes APT actifs, lessons learned. Référence mondiale.",
      notes: "Sortie en avril chaque année. Gratuit. À lire absolument pour calibrer ses scénarios pédagogiques sur la réalité du terrain."
    },
    {
      id: 'crowdstrike-globalthreat',
      title: 'CrowdStrike Global Threat Report',
      authors: 'CrowdStrike Intelligence',
      editor: 'crowdstrike.com',
      year: 2025,
      category: 'Malware / Reverse',
      language: 'en',
      level: 'référence',
      format: 'Rapport',
      url: 'https://www.crowdstrike.com/global-threat-report/',
      tags: ['APT', 'eCrime', 'breakout time'],
      description: "Rapport annuel équivalent M-Trends côté CrowdStrike. Insight sur les groupes nommés (BEAR, PANDA, KITTEN, SPIDER), le 'breakout time' (durée entre infection initiale et mouvement latéral).",
      notes: "Vision plus eCrime (ransomware, fraude) que Mandiant qui est plus nation-state. Les deux sont complémentaires."
    },

    // ═══════════════════════ CLOUD / SAAS FORENSICS ═══════════════════════
    {
      id: 'm365-purview',
      title: 'Microsoft Purview Audit (Premium) Documentation',
      authors: 'Microsoft',
      editor: 'learn.microsoft.com',
      year: 2024,
      category: 'Cloud / SaaS',
      language: 'en',
      level: 'intermédiaire',
      format: 'Standard',
      url: 'https://learn.microsoft.com/en-us/purview/audit-premium',
      tags: ['M365', 'Purview', 'audit', 'eDiscovery', 'Copilot'],
      description: "Documentation officielle Microsoft Purview Audit. Capacités d'audit M365 : événements Standard 180j, Premium 10 ans (avec E5). Couvre Exchange, SharePoint, Teams, Copilot interactions.",
      notes: "Essentiel pour investiguer un incident M365. La différence Standard/Premium est cruciale pour la rétention. Voir aussi la PowerShell ExchangeOnlineManagement pour les requêtes massives."
    },
    {
      id: 'aws-forensics-wp',
      title: 'AWS Security Incident Response Guide',
      authors: 'AWS',
      editor: 'docs.aws.amazon.com',
      year: 2023,
      category: 'Cloud / SaaS',
      language: 'en',
      level: 'intermédiaire',
      format: 'Standard',
      url: 'https://docs.aws.amazon.com/security-ir/latest/userguide/',
      tags: ['AWS', 'cloud forensics', 'CloudTrail', 'GuardDuty'],
      description: "Guide officiel AWS d'incident response. CloudTrail, GuardDuty, VPC Flow Logs, isolation EC2, snapshots EBS pour analyse forensique offline.",
      notes: "Compléter avec le Whitepaper 'Forensic Investigation' AWS. Pour Azure : 'Azure Sentinel' docs ; pour GCP : 'Security Command Center'."
    },
    {
      id: 'invictus-cloud',
      title: 'Invictus IR Cloud Forensics Blog',
      authors: 'Invictus Incident Response',
      editor: 'invictus-ir.com',
      year: 2024,
      category: 'Cloud / SaaS',
      language: 'en',
      level: 'avancé',
      format: 'Blog',
      url: 'https://www.invictus-ir.com/news',
      tags: ['M365', 'Azure', 'AWS', 'Google Workspace', 'IR cloud'],
      description: "Blog très opérationnel sur l'IR cloud. Tutoriels concrets sur Microsoft Unified Audit Log, recherches Compliance/eDiscovery, abus Graph API. Très utilisé après affaires Octo Tempest.",
      notes: "Articles dense et pratiques. Voir leur dépôt GitHub Microsoft-Extractor-Suite (PowerShell + Python pour extraction logs M365)."
    },

    // ═══════════════════════ IA / LLM FORENSIQUE ═══════════════════════
    {
      id: 'owasp-llm-top10',
      title: 'OWASP Top 10 for LLM Applications 2025',
      authors: 'OWASP Foundation',
      editor: 'genai.owasp.org',
      year: 2024,
      category: 'IA / LLM',
      language: 'en',
      level: 'référence',
      format: 'Standard',
      url: 'https://genai.owasp.org/llm-top-10/',
      tags: ['OWASP', 'LLM', 'prompt injection', 'AI security'],
      description: "Cartographie des 10 risques majeurs des applications LLM : Prompt Injection, Sensitive Information Disclosure, Supply Chain, Data/Model Poisoning, Improper Output Handling, Excessive Agency, System Prompt Leakage, Vector & Embedding Weaknesses, Misinformation, Unbounded Consumption.",
      notes: "Publié novembre 2024. Désormais utilisé par les régulateurs (EU AI Act, NIST AI RMF) et les éditeurs (OpenAI, Anthropic, Google, Microsoft). À comparer à l'OWASP Top 10 web classique."
    },
    {
      id: 'anthropic-opus-systemcard',
      title: 'Claude Opus 4.6 System Card',
      authors: 'Anthropic',
      editor: 'anthropic.com',
      year: 2026,
      category: 'IA / LLM',
      language: 'en',
      level: 'avancé',
      format: 'Rapport',
      url: 'https://www.anthropic.com/news/claude-opus-4-6-system-card',
      tags: ['Anthropic', 'system card', 'AI safety', 'jailbreak'],
      description: "Carte système Claude Opus 4.6 (212 pages, février 2026). Premier rapport public à quantifier les taux de succès de prompt injection par environnement : 17.8% sur GUI avec extended thinking sans safeguards, 78.6% à 200 tentatives. Standard de transparence frontier AI.",
      notes: "Référence pour comprendre quantitativement les risques LLM. Anthropic publie une system card pour chaque release. À comparer à la System Card OpenAI GPT-5 et au Frontier Model Forum."
    },
    {
      id: 'nist-ai-100-2',
      title: 'NIST AI 100-2 E2025: Adversarial Machine Learning Taxonomy',
      authors: 'NIST',
      editor: 'nist.gov',
      year: 2025,
      category: 'IA / LLM',
      language: 'en',
      level: 'avancé',
      format: 'Standard',
      url: 'https://csrc.nist.gov/publications/detail/sp/800-100/2/final',
      tags: ['NIST', 'adversarial ML', 'taxonomie'],
      description: "Taxonomie officielle NIST des attaques contre l'IA : evasion, poisoning, model extraction, prompt injection. Référence pour structurer une analyse de risque IA.",
      notes: "Document dense. Lire les chapitres pertinents au LLM/GenAI si on n'a pas le temps."
    },
    {
      id: 'enisa-ai-mlfgcsp',
      title: 'Multilayer Framework for Good Cybersecurity Practices for AI',
      authors: 'ENISA',
      editor: 'enisa.europa.eu',
      year: 2023,
      category: 'IA / LLM',
      language: 'en',
      level: 'intermédiaire',
      format: 'Standard',
      url: 'https://www.enisa.europa.eu/publications/multilayer-framework-for-good-cybersecurity-practices-for-ai',
      tags: ['ENISA', 'UE', 'AI cybersecurity'],
      description: "Cadre ENISA (agence UE cybersécurité) pour la sécurité des systèmes IA. Couvre tout le cycle de vie, complémentaire à NIST AI RMF.",
      notes: "Particulièrement utile dans le contexte de l'AI Act UE qui s'appuie sur ces orientations."
    },
    {
      id: 'citizenlab',
      title: 'The Citizen Lab Research',
      authors: 'Citizen Lab (University of Toronto)',
      editor: 'citizenlab.ca',
      year: 2024,
      category: 'IA / LLM',
      language: 'en',
      level: 'avancé',
      format: 'Blog',
      url: 'https://citizenlab.ca/',
      tags: ['spyware', 'Pegasus', 'Predator', 'NSO', 'mobile'],
      description: "Recherche académique sur les outils de surveillance étatique : Pegasus (NSO), Predator (Intellexa), Triangulation iOS. Publications avec preuves techniques rigoureuses.",
      notes: "Source primaire pour comprendre les implants mobiles modernes. Travaillent avec Amnesty Tech (MVT - Mobile Verification Toolkit)."
    },

    // ═══════════════════════ DROIT SUISSE ═══════════════════════
    {
      id: 'cp-suisse',
      title: 'Code pénal suisse (RS 311.0)',
      authors: 'Confédération suisse',
      editor: 'fedlex.admin.ch',
      year: 2024,
      category: 'Droit suisse',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://www.fedlex.admin.ch/eli/cc/54/757_781_799/fr',
      tags: ['CP', 'art. 143', 'art. 144bis', 'art. 156', 'art. 117', 'art. 197', 'art. 305bis'],
      description: "Code pénal suisse. Articles centraux DFIR : 143 (soustraction de données), 143bis (accès indu), 144bis (détérioration), 147 (utilisation frauduleuse ordinateur), 156 (extorsion), 173-177 (atteintes à l'honneur), 197 (pornographie), 305bis (blanchiment).",
      notes: "Consulter Fedlex pour la version officielle à jour. Existe en DE/FR/IT/RM. Doctrine : Stratenwerth-Wohlers Schweizerisches Strafrecht (Stämpfli)."
    },
    {
      id: 'cpp-suisse',
      title: 'Code de procédure pénale suisse (RS 312.0)',
      authors: 'Confédération suisse',
      editor: 'fedlex.admin.ch',
      year: 2024,
      category: 'Droit suisse',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://www.fedlex.admin.ch/eli/cc/2010/267/fr',
      tags: ['CPP', 'art. 158', 'art. 244-248', 'art. 269-279', 'TMC', 'scellés'],
      description: "Code de procédure pénale (en vigueur 2011). Articles essentiels : 158 (droits du prévenu), 244-248 (perquisition + scellés), 269-279 (surveillance correspondance), 280 (moyens techniques), 197 (proportionnalité).",
      notes: "La révision 2024 a modifié plusieurs dispositions surveillance et secret. Voir aussi l'OEIMP et l'OSCPT pour les modalités."
    },
    {
      id: 'nlpd',
      title: 'Loi fédérale sur la protection des données (nLPD, RS 235.1)',
      authors: 'Confédération suisse',
      editor: 'fedlex.admin.ch',
      year: 2023,
      category: 'Droit suisse',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://www.fedlex.admin.ch/eli/cc/2022/491/fr',
      tags: ['nLPD', 'protection données', 'PFPDT'],
      description: "Nouvelle Loi fédérale sur la protection des données. En vigueur depuis le 1er septembre 2023. Aligne partiellement la CH sur le RGPD. Art. 5 (définitions), art. 24 (notification 72h), art. 60-65 (sanctions pénales max 250'000 CHF).",
      notes: "Différences clés vs RGPD : sanctions pénales contre personnes physiques (pas amendes administratives 4% CA). Voir guide PFPDT pour application pratique."
    },
    {
      id: 'lscpt',
      title: 'LSCPT — Loi sur la surveillance correspondance (RS 780.1)',
      authors: 'Confédération suisse',
      editor: 'fedlex.admin.ch',
      year: 2018,
      category: 'Droit suisse',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://www.fedlex.admin.ch/eli/cc/2018/27/fr',
      tags: ['LSCPT', 'rétention', 'SCPT', 'OSCPT'],
      description: "Cadre légal de la surveillance des télécommunications en Suisse. Rétention métadonnées : 6 mois cellules mobiles, 12 mois identifiants Internet (art. 26 OSCPT). Procédure via le Service de surveillance (SCPT, Berne).",
      notes: "Indispensable pour comprendre ce qui est ou n'est pas accessible aux enquêteurs. Voir aussi ATF récents sur la légalité des données rétroactives."
    },
    {
      id: 'lsi',
      title: 'LSI — Loi sur la sécurité de l\'information (RS 128)',
      authors: 'Confédération suisse',
      editor: 'fedlex.admin.ch',
      year: 2025,
      category: 'Droit suisse',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://www.fedlex.admin.ch/eli/cc/2022/232/fr',
      tags: ['LSI', 'OFCS', 'NCSC', 'signalement 24h', 'OCyS'],
      description: "Obligations de signalement des cyberattaques pour les infrastructures critiques. Art. 74b (assujettis), 74e (obligation 24h à l'OFCS), 74g (sanctions ≤ 100'000 CHF). Entrée en vigueur 1.4.2025.",
      notes: "Complétée par l'OCyS (Ordonnance sur la cybersécurité). Plateforme de signalement : report.ncsc.admin.ch."
    },
    {
      id: 'eimp',
      title: 'EIMP — Loi sur l\'entraide pénale internationale (RS 351.1)',
      authors: 'Confédération suisse',
      editor: 'fedlex.admin.ch',
      year: 2024,
      category: 'Droit suisse',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://www.fedlex.admin.ch/eli/cc/1982/846_846_846/fr',
      tags: ['EIMP', 'OFJ', 'MLAT', 'entraide'],
      description: "Cadre suisse de l'entraide pénale internationale. Autorité centrale : OFJ (Office fédéral de la justice). Couvre les demandes actives et passives, conditions de double incrimination, principe de spécialité.",
      notes: "À combiner avec la Convention européenne d'entraide judiciaire en matière pénale (1959 + 2e protocole 2001), et avec la Convention de Budapest art. 32 pour la préservation 24/7."
    },
    {
      id: 'metille-nlpd',
      title: 'La protection des données personnelles dans l\'entreprise',
      authors: 'Sylvain Métille',
      editor: 'Schulthess Éditions Romandes',
      year: 2025,
      category: 'Droit suisse',
      language: 'fr',
      level: 'avancé',
      format: 'Livre',
      tags: ['nLPD', 'entreprise', 'compliance', 'PFPDT'],
      description: "Manuel pratique de droit de la protection des données suisse en entreprise. Sylvain Métille est avocat (HDC), enseigne à l'UNIL et est l'une des principales références romandes en nLPD.",
      notes: "À jour avec la nLPD 2023. Aborde notamment la transposition pratique, les transferts internationaux, les notifications PFPDT."
    },
    {
      id: 'swissprivacy-law',
      title: 'swissprivacy.law (revue & blog)',
      authors: 'Communauté académique CH',
      editor: 'swissprivacy.law',
      year: 2024,
      category: 'Droit suisse',
      language: 'fr',
      level: 'intermédiaire',
      format: 'Blog',
      url: 'https://swissprivacy.law/',
      tags: ['nLPD', 'PFPDT', 'jurisprudence', 'doctrine'],
      description: "Blog de référence en droit suisse de la protection des données. Auteurs : universitaires UNIGE, UNIL, UZH. Articles courts, juridiquement rigoureux, gratuits.",
      notes: "Excellent pour suivre l'actualité nLPD et la doctrine émergente. Indexé par mot-clé et auteur."
    },
    {
      id: 'cdbf-ch',
      title: 'Centre de droit bancaire et financier (cdbf.ch)',
      authors: 'Université de Genève',
      editor: 'cdbf.ch',
      year: 2024,
      category: 'Droit suisse',
      language: 'fr',
      level: 'avancé',
      format: 'Blog',
      url: 'https://cdbf.ch/',
      tags: ['LBA', 'FINMA', 'MROS', 'fraude'],
      description: "Centre de l'Université de Genève sur le droit bancaire et financier. Commentaires d'arrêts récents, notamment sur LBA, MROS, fraudes crypto, cyber-extorsion contre établissements financiers.",
      notes: "Particulièrement utile pour les volets blanchiment / cyber-crime contre institutions financières."
    },
    {
      id: 'pfpdt',
      title: 'PFPDT — Recommandations et guides',
      authors: 'Préposé fédéral à la protection des données',
      editor: 'edoeb.admin.ch',
      year: 2024,
      category: 'Droit suisse',
      language: 'fr',
      level: 'référence',
      format: 'Standard',
      url: 'https://www.edoeb.admin.ch/edoeb/fr/home.html',
      tags: ['PFPDT', 'nLPD', 'recommandations', 'AIPD'],
      description: "Autorité fédérale de surveillance nLPD. Publie guides, modèles AIPD (analyses d'impact), FAQ, décisions. Source officielle pour l'application pratique de la nLPD.",
      notes: "Lire en priorité : guide sur les notifications de violation art. 24 nLPD, et les recommandations sur les transferts internationaux."
    },

    // ═══════════════════════ DROIT UE / INTERNATIONAL ═══════════════════════
    {
      id: 'rgpd',
      title: 'RGPD — Règlement UE 2016/679',
      authors: 'Union européenne',
      editor: 'eur-lex.europa.eu',
      year: 2016,
      category: 'Droit UE / International',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
      tags: ['RGPD', 'GDPR', 'CNIL', 'EDPB'],
      description: "Règlement Général sur la Protection des Données. Application directe dans l'UE depuis 25.5.2018. Effet extraterritorial sur entreprises CH ciblant le marché UE.",
      notes: "Compléter avec les lignes directrices de l'EDPB (European Data Protection Board). Pour la CH : effet indirect via clauses contractuelles + reconnaissance d'adéquation."
    },
    {
      id: 'nis2',
      title: 'NIS2 — Directive UE 2022/2555',
      authors: 'Union européenne',
      editor: 'eur-lex.europa.eu',
      year: 2022,
      category: 'Droit UE / International',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
      tags: ['NIS2', 'cybersécurité', 'infrastructures essentielles'],
      description: "Directive UE sur la cybersécurité des infrastructures essentielles et importantes. Remplace NIS1. Transposition nationale obligatoire depuis octobre 2024. Inspire la LSI suisse.",
      notes: "Pas applicable directement en CH, mais effet via filiales et partenaires UE. Critère taille 250 emp / 50M€ CA = très large."
    },
    {
      id: 'dsa',
      title: 'DSA — Digital Services Act (Règlement UE 2022/2065)',
      authors: 'Union européenne',
      editor: 'eur-lex.europa.eu',
      year: 2022,
      category: 'Droit UE / International',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://eur-lex.europa.eu/eli/reg/2022/2065/oj',
      tags: ['DSA', 'VLOP', 'plateforme', 'modération'],
      description: "Régulation des plateformes numériques. VLOPs (>45M utilisateurs UE) : TikTok, Meta, X, Google, Apple, etc. Art. 16 (signalement), 28 (mineurs), 34-35 (risques systémiques), 40 (chercheurs).",
      notes: "Très utile pour comprendre les obligations TikTok/Meta dans des affaires comme 'L'Affaire Tom' (DFIR + mineurs)."
    },
    {
      id: 'ai-act',
      title: 'AI Act — Règlement UE 2024/1689',
      authors: 'Union européenne',
      editor: 'eur-lex.europa.eu',
      year: 2024,
      category: 'Droit UE / International',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
      tags: ['AI Act', 'IA', 'risque', 'biométrie'],
      description: "Premier cadre légal global de l'IA. Approche par les risques : inacceptable / élevé / limité / minimal. Obligations spécifiques sur la biométrie, IA générative, modèles à usage général.",
      notes: "Application progressive 2025-2027. Effet extraterritorial. Sanctions jusqu'à 7% CA mondial pour les pratiques interdites."
    },
    {
      id: 'budapest-convention',
      title: 'Convention sur la cybercriminalité (Budapest, 2001)',
      authors: 'Conseil de l\'Europe',
      editor: 'coe.int',
      year: 2001,
      category: 'Droit UE / International',
      language: 'fr',
      level: 'référence',
      format: 'Loi',
      url: 'https://www.coe.int/fr/web/cybercrime/the-budapest-convention',
      tags: ['Budapest', 'cybercrime', 'art. 32', 'préservation'],
      description: "Convention internationale de référence pour la cybercriminalité. 70+ pays signataires. Art. 32 = préservation transfrontière 24/7, art. 26 = informations spontanées. Suisse partie depuis 2012.",
      notes: "2e protocole additionnel adopté 2022 (production transfrontière directe, garanties). Pivot juridique de quasi tous les cas DFIR transfrontières."
    },

    // ═══════════════════════ STANDARDS ═══════════════════════
    {
      id: 'iso-27037',
      title: 'ISO/IEC 27037:2012',
      authors: 'ISO/IEC',
      editor: 'iso.org',
      year: 2012,
      category: 'Standards',
      language: 'en',
      level: 'référence',
      format: 'Standard',
      url: 'https://www.iso.org/standard/44381.html',
      tags: ['ISO', 'acquisition', 'preuve numérique', 'DEFR', 'DES'],
      description: "Standard international pour l'identification, la collecte, l'acquisition et la préservation des preuves numériques. Définit les rôles DEFR (First Responder), DES (Specialist).",
      notes: "Souvent invoqué en CH par les experts forensiques pour démontrer le respect des bonnes pratiques. Payant (~CHF 200), mais beaucoup d'établissements ont accès via leur bibliothèque universitaire."
    },
    {
      id: 'iso-27041',
      title: 'ISO/IEC 27041:2015',
      authors: 'ISO/IEC',
      editor: 'iso.org',
      year: 2015,
      category: 'Standards',
      language: 'en',
      level: 'référence',
      format: 'Standard',
      url: 'https://www.iso.org/standard/44405.html',
      tags: ['ISO', 'investigation', 'méthodologie'],
      description: "Complète 27037. Couvre l'assurance qualité de la méthode d'investigation : choix d'outils, reproductibilité, validation.",
      notes: "Lire ensemble : 27037 (preuve), 27041 (méthode), 27042 (analyse), 27043 (incident investigation principles). Famille cohérente."
    },
    {
      id: 'iso-27042',
      title: 'ISO/IEC 27042:2015',
      authors: 'ISO/IEC',
      editor: 'iso.org',
      year: 2015,
      category: 'Standards',
      language: 'en',
      level: 'référence',
      format: 'Standard',
      url: 'https://www.iso.org/standard/44406.html',
      tags: ['ISO', 'analyse', 'interprétation'],
      description: "Analyse et interprétation des preuves numériques. Modèles d'analyse, biais cognitifs, reporting.",
      notes: "Moins utilisé en pratique que 27037 mais important pour la formation à l'expertise."
    },
    {
      id: 'nist-800-86',
      title: 'NIST SP 800-86: Guide to Integrating Forensic Techniques',
      authors: 'NIST',
      editor: 'nist.gov',
      year: 2006,
      category: 'Standards',
      language: 'en',
      level: 'référence',
      format: 'Standard',
      url: 'https://csrc.nist.gov/publications/detail/sp/800-86/final',
      tags: ['NIST', 'forensique', 'IR', 'gratuit'],
      description: "Guide NIST gratuit (US government) pour intégrer les techniques forensiques à la réponse incident. Couvre acquisition, examen, analyse, reporting.",
      notes: "Gratuit, accessible, complémentaire à ISO 27037. Standard de fait dans le monde anglophone."
    },
    {
      id: 'nist-800-101',
      title: 'NIST SP 800-101r1: Guidelines on Mobile Device Forensics',
      authors: 'NIST',
      editor: 'nist.gov',
      year: 2014,
      category: 'Standards',
      language: 'en',
      level: 'référence',
      format: 'Standard',
      url: 'https://csrc.nist.gov/publications/detail/sp/800-101/rev-1/final',
      tags: ['NIST', 'mobile', 'iOS', 'Android'],
      description: "Guide NIST pour la forensique mobile. Outils, méthodes d'acquisition (manuelle, logique, physique, chip-off), considérations chiffrement.",
      notes: "Daté sur les outils spécifiques mais les principes restent valides. Pour les modèles récents, croiser avec la documentation Cellebrite/Magnet."
    },
    {
      id: 'rfc-3227',
      title: 'RFC 3227: Guidelines for Evidence Collection and Archiving',
      authors: 'IETF',
      editor: 'ietf.org',
      year: 2002,
      category: 'Standards',
      language: 'en',
      level: 'référence',
      format: 'Standard',
      url: 'https://datatracker.ietf.org/doc/html/rfc3227',
      tags: ['RFC', 'IETF', 'ordre de volatilité', 'chain of custody'],
      description: "RFC IETF qui établit l'ordre de volatilité (CPU registers → RAM → état réseau → disque → distant → archives). Référence historique mais toujours citée.",
      notes: "Court (8 pages), gratuit, à connaître par cœur pour tout examen DFIR. L'ordre de volatilité guide encore les acquisitions."
    },
    {
      id: 'swgde',
      title: 'SWGDE — Scientific Working Group on Digital Evidence',
      authors: 'SWGDE',
      editor: 'swgde.org',
      year: 2024,
      category: 'Standards',
      language: 'en',
      level: 'référence',
      format: 'Standard',
      url: 'https://www.swgde.org/documents',
      tags: ['SWGDE', 'best practices', 'gratuit'],
      description: "Groupe scientifique américain sur la preuve numérique. Publie des Best Practices gratuits sur l'imaging, le hashing, le mobile forensics, l'audio, la vidéo, etc.",
      notes: "Tous les documents sont gratuits. Particulièrement utiles : Best Practices for Computer Forensic Examinations, Best Practices for Mobile Device Evidence Preservation."
    },

    // ═══════════════════════ BLOGS / SITES / PODCASTS ═══════════════════════
    {
      id: 'sans-dfir-blog',
      title: 'SANS DFIR Blog',
      authors: 'SANS Institute',
      editor: 'sans.org',
      year: 2024,
      category: 'Blogs / Podcasts',
      language: 'en',
      level: 'référence',
      format: 'Blog',
      url: 'https://www.sans.org/blog/?focus-area=digital-forensics',
      tags: ['SANS', 'DFIR', 'tutoriels'],
      description: "Blog officiel SANS DFIR. Articles techniques par les instructeurs (Heather Mahalik, Rob Lee, Phil Hagen, Sarah Edwards, Hal Pomeranz, etc.). Posters téléchargeables gratuitement.",
      notes: "Les posters SANS (Windows, Linux, macOS, Mobile, Cloud, ICS) sont des aides-mémoire de qualité, gratuits, à imprimer."
    },
    {
      id: 'hexacorn',
      title: 'Hexacorn blog',
      authors: 'Adam Hexacorn',
      editor: 'hexacorn.com',
      year: 2024,
      category: 'Blogs / Podcasts',
      language: 'en',
      level: 'avancé',
      format: 'Blog',
      url: 'https://www.hexacorn.com/blog/',
      tags: ['Windows', 'persistance', 'artefacts obscurs'],
      description: "Blog mythique sur les artefacts Windows obscurs. Série 'Beyond good ol' Run key' (persistance), recherches sur LOLBins, AmSI, AppCompat. Très technique.",
      notes: "Pour les chercheurs avancés. Les techniques de persistance documentées ici se retrouvent ensuite dans MITRE ATT&CK."
    },
    {
      id: 'risky-biz',
      title: 'Risky Business Podcast',
      authors: 'Patrick Gray',
      editor: 'risky.biz',
      year: 2024,
      category: 'Blogs / Podcasts',
      language: 'en',
      level: 'intermédiaire',
      format: 'Podcast',
      url: 'https://risky.biz/',
      tags: ['podcast', 'cybersécurité', 'actualité'],
      description: "Podcast hebdomadaire de référence en cybersécurité depuis 2007. Patrick Gray (journaliste AU) interviewe vendeurs, chercheurs, decision-makers. News commentées, focus geo-politique.",
      notes: "Format ~1h30/semaine. Aussi 'Risky Business News' (quotidien court). Excellent pour rester à jour."
    },
    {
      id: 'darknet-diaries',
      title: 'Darknet Diaries Podcast',
      authors: 'Jack Rhysider',
      editor: 'darknetdiaries.com',
      year: 2024,
      category: 'Blogs / Podcasts',
      language: 'en',
      level: 'intro',
      format: 'Podcast',
      url: 'https://darknetdiaries.com/',
      tags: ['podcast', 'storytelling', 'cas réels'],
      description: "Podcast de narratifs d'affaires cyber réelles. Format storytelling, interviews acteurs (hackers, victimes, IR teams). Excellent vulgarisation, sans technicité excessive.",
      notes: "Idéal pour transmettre la culture DFIR à des étudiants ou un public général. Plusieurs épisodes sur des affaires CH/EU."
    },
    {
      id: 'forensicfocus',
      title: 'Forensic Focus',
      authors: 'Communauté',
      editor: 'forensicfocus.com',
      year: 2024,
      category: 'Blogs / Podcasts',
      language: 'en',
      level: 'intermédiaire',
      format: 'Blog',
      url: 'https://www.forensicfocus.com/',
      tags: ['communauté', 'forum', 'jobs', 'articles'],
      description: "Site communautaire majeur en DFIR depuis 1999. Articles, interviews vendeurs, forum (toujours actif), offres d'emploi internationales.",
      notes: "Une référence historique. Forum encore utile pour des questions très spécifiques sur outils commerciaux."
    },
    {
      id: 'dfirreport',
      title: 'The DFIR Report',
      authors: 'The DFIR Report (équipe collaborative)',
      editor: 'thedfirreport.com',
      year: 2024,
      category: 'Blogs / Podcasts',
      language: 'en',
      level: 'avancé',
      format: 'Blog',
      url: 'https://thedfirreport.com/',
      tags: ['ransomware', 'IR', 'TTP', 'IOC'],
      description: "Rapports détaillés d'intrusions ransomware réelles : initial access → lateral → impact, avec TTPs MITRE, IOCs, timeline. Gratuits, très exploitable pour défense.",
      notes: "Source primaire pour comprendre les opérations ransomware modernes (Conti, LockBit, Black Basta, Akira). Format mensuel."
    },
    {
      id: 'ncsc-ofcs',
      title: 'OFCS / NCSC Suisse — Rapports semestriels',
      authors: 'Office fédéral de la cybersécurité',
      editor: 'ncsc.admin.ch',
      year: 2025,
      category: 'Blogs / Podcasts',
      language: 'fr',
      level: 'référence',
      format: 'Rapport',
      url: 'https://www.ncsc.admin.ch/ncsc/fr/home/dokumentation/rapports/rapports-de-situation.html',
      tags: ['Suisse', 'OFCS', 'rapport semestriel'],
      description: "Rapports semestriels officiels de l'OFCS sur la situation cyber en Suisse. Statistiques de signalements (escroquerie investissement, ransomware, fuite de données, etc.). Disponibles FR/DE/IT/EN.",
      notes: "Indispensables pour le contexte CH. Donnent les chiffres officiels (ex. 3'485 signalements escroqueries investissement S1 2025)."
    },
    {
      id: 'swisscyberinstitute',
      title: 'Swiss Cyber Institute',
      authors: 'SCI',
      editor: 'swisscyberinstitute.com',
      year: 2024,
      category: 'Blogs / Podcasts',
      language: 'en',
      level: 'intro',
      format: 'Blog',
      url: 'https://swisscyberinstitute.com/blog/',
      tags: ['Suisse', 'cybersécurité', 'CTF', 'communauté'],
      description: "Institut suisse privé. Blog en anglais sur la cybersécurité, organise CTF, conférences. Cible plutôt l'écosystème CH industriel.",
      notes: "Pour le réseau professionnel CH cyber. Voir aussi Swisscom Cybersecurity Threat Radar."
    },

    // ═══════════════════════ CONFÉRENCES ═══════════════════════
    {
      id: 'dfrws',
      title: 'DFRWS — Digital Forensics Research Workshop',
      authors: 'DFRWS',
      editor: 'dfrws.org',
      year: 2024,
      category: 'Conférences',
      language: 'en',
      level: 'avancé',
      format: 'Conférence',
      url: 'https://dfrws.org/',
      tags: ['conférence', 'académique', 'recherche'],
      description: "Conférence académique de référence en DFIR. Deux éditions annuelles (USA + EU). Articles peer-reviewed publiés dans Forensic Science International: Digital Investigation (Elsevier).",
      notes: "Publications gratuites archivées. Niveau recherche, mais les CFP/proceedings indiquent les sujets émergents (cloud, IoT, IA forensique)."
    },
    {
      id: 'sans-summit',
      title: 'SANS DFIR Summit',
      authors: 'SANS',
      editor: 'sans.org',
      year: 2024,
      category: 'Conférences',
      language: 'en',
      level: 'avancé',
      format: 'Conférence',
      url: 'https://www.sans.org/cyber-security-training-events/dfir-summit/',
      tags: ['SANS', 'praticien', 'industrie'],
      description: "Summit DFIR annuel SANS (Austin, TX, fin juin). Présentations praticiens d'IR teams (Mandiant, CrowdStrike, etc.) sur incidents anonymisés. Très opérationnel.",
      notes: "Talks souvent enregistrés et publiés sur YouTube SANS DFIR (gratuit, plusieurs mois après). Source unique d'expérience IR de terrain."
    },
    {
      id: 'first',
      title: 'FIRST Annual Conference',
      authors: 'FIRST',
      editor: 'first.org',
      year: 2024,
      category: 'Conférences',
      language: 'en',
      level: 'avancé',
      format: 'Conférence',
      url: 'https://www.first.org/conference/',
      tags: ['FIRST', 'CSIRT', 'CERT', 'coopération'],
      description: "Conférence de référence pour les équipes CSIRT/CERT du monde entier (~600 équipes membres FIRST). Coopération technique, partage TI, IR cross-border.",
      notes: "GovCERT.ch et CERT-Bund participent. Talks souvent enregistrés, archive FIRST.org accessible."
    },
    {
      id: 'bsides-geneva',
      title: 'BSides Geneva / Zurich',
      authors: 'Communauté CH',
      editor: 'bsides.ch',
      year: 2024,
      category: 'Conférences',
      language: 'en',
      level: 'intermédiaire',
      format: 'Conférence',
      url: 'https://www.bsides.ch/',
      tags: ['BSides', 'Suisse', 'communauté'],
      description: "Édition suisse des conférences communautaires BSides. Talks de chercheurs, praticiens, étudiants. Plus accessible que Black Hat / DEF CON. Networking local.",
      notes: "Bon point d'entrée à la communauté cyber CH. Insomni'hack (Genève, mars) est aussi une référence locale."
    },
    {
      id: 'insomnihack',
      title: 'Insomni\'hack (Genève)',
      authors: 'SCRT',
      editor: 'insomnihack.ch',
      year: 2024,
      category: 'Conférences',
      language: 'en',
      level: 'intermédiaire',
      format: 'Conférence',
      url: 'https://insomnihack.ch/',
      tags: ['CTF', 'Genève', 'Suisse', 'sécurité offensive'],
      description: "Conférence + CTF majeur de l'écosystème cyber suisse, organisé par SCRT à Genève depuis 2008. Plutôt orientation offensive/red team mais talks DFIR aussi.",
      notes: "Le CTF Finals (présentiel) est l'un des plus exigeants d'Europe. Networking incontournable pour la scène cyber romande."
    },
  ]
};
