"""Étoffe tous les distracteurs des 4 scènes cas réels pour atteindre ratio < 1.5.

Stratégie : ajouter à chaque distracteur un suffixe de détail technique apparemment
crédible mais qui ne change pas la nature 'mauvais choix' de la décision. Le détail
ajouté reste cohérent avec la mauvaise décision (justifications faussement plausibles,
références normatives mal appliquées, étapes procédurales détaillées mais menant
quand même à la mauvaise issue).

Approche : pour chaque scène, parcourir les steps, identifier les choix non-ok,
et leur ajouter un padding contextuel d'environ 600-900 chars chacun.
"""
import json
from pathlib import Path

# ── Padding par scène/step ───────────────────────────────────────
# Format: { scene_id : { step_idx (0-based) : [pad_for_distractor_1, pad_for_distractor_2] } }
# La structure suit l'ordre des choix dans le step (le choix ok est sauté).

PADDINGS = {
    # ═══════════════ CRYPTO AG ═══════════════
    "crypto-ag-rubikon-enquete-dfir-2020": {
        # Step 0 — compétence MPC
        0: [
            # Distracteur 1 : non-entrée en matière
            " Argumentaire complémentaire : la procédure cantonale ZG dispose d'un département pénal éco renforcé depuis 2018, capable techniquement de traiter le dossier. La doctrine MPC 2018 (rapport Lauber) recommande de ne pas saisir la juridiction fédérale quand une juridiction cantonale a la compétence ratione loci et les moyens. Communication MPC publique : 'compétence cantonale retenue, faits historiquement complexes, prescription couvrant la majorité des faits — voie de redevabilité parlementaire DélCdG appropriée'. Annexe juridique au dossier DélCdG pour leur permettre de continuer leur travail. Renvoi formel daté du 5 mars 2020, dossier 320 pages avec analyse prescription par exercice annuel 1996-2018, transmission par voie administrative au procureur cantonal ZG (Me Marc Eberle).",
            # Distracteur 2 : instruction formelle anticipée
            " Plan opérationnel détaillé : ouverture d'instruction formelle le 5 mars 2020 avec calendrier serré — auditions des CF actuels et anciens entre mars et mai (5 auditions), auditions des anciens dirigeants Crypto AG et SRC entre avril-juin (8 auditions), expertises forensique externes mandatées en parallèle (Cyber-Defense Campus Thoune). Communication publique synchronisée : conférence de presse fedpol-MPC le 6 mars 2020 annonçant l'instruction formelle avec liste des chefs (art. 273 CP, 271 CP, 14 LCB) et identités des prévenus pour 'transparence démocratique'. Demande au Parlement de levée d'immunité Amherd via Bureau Conseil national pour audition formelle prévenue (art. 158 CPP) entre 15-22 avril. Coordination publique avec DélCdG pour synergies et auditions conjointes."
        ],
        # Step 1 — analyse forensique
        1: [
            # Distracteur 1 : minimaliste
            " Justification : le rapport DélCdG du 10 novembre 2020 s'appuiera sur le rapport Oberholzer (classifié) qui dispose déjà de tous les détails techniques nécessaires — dupliquer cette analyse au MPC est redondance institutionnelle. Stratégie : focus sur l'analyse documentaire des sources publiques disponibles (Friedman Collection NSA 2014 — 7'600 documents, 52'000 pages déclassifiés ; rapports ZDF Rundschau février 2020 ; reportages SRF/RTS février 2020 ; documents Hans Bühler post-libération Iran 1992 ; Baltimore Sun décembre 1995). Synthèse technique en 60 pages signée du chef SCS, valeur juridique d'expertise interne fedpol. Économie estimée : CHF 380'000 vs CHF 1.2M pour analyse complète. Calendrier compatible avec décision MPC mi-2021.",
            # Distracteur 2 : Citizen Lab/EFF
            " Composition du consortium international : Citizen Lab (Université de Toronto, Pr. Ron Deibert) lead pour la couche forensique hardware (15 ans d'expertise sur outils étatiques type Pegasus, FinFisher, Hacking Team) ; EFF (Electronic Frontier Foundation San Francisco) coordonnant la couche cryptanalyse algorithmique (équipe Cryptography & Privacy Engineering, Pr. Bruce Schneier consultant) ; consortium académique Stanford-MIT-EPFL-ETHZ pour la validation indépendante. Mandat formel art. 184 CPP avec habilitation secret défense temporaire. Observateurs : 1 représentant par État historiquement espionné (Iran, Argentine, Lybie, Égypte, Indonésie, Vatican, Saint-Marin), accord de confidentialité signé. Publication progressive : un livrable technique par mois sur site MPC dédié + conférences publiques semestrielles. Objectif communicationnel : restaurer la réputation internationale CH compromise par les révélations 2020, démontrer la maturité institutionnelle CH face aux héritages problématiques."
        ],
        # Step 2 — coordination DélCdG
        2: [
            # Distracteur 1 : audition prévenue Amherd
            " Justification politique : la CH ne peut pas montrer une justice à deux vitesses (protection des ministres vs poursuite des subalternes). L'audition prévenue d'Amherd au titre art. 312 CP (défaut de surveillance — elle dirigeait le DDPS et donc tutelle SRC pendant la période finale 2019-2020) est une affirmation forte de l'égalité républicaine. Demande formelle de levée d'immunité au Bureau Conseil national avec mémoire juridique 45 pages. Coordination préalable avec Présidence Conseil fédéral pour préparer la communication. Suspension temporaire des fonctions Amherd pendant l'instruction (art. 96 al. 2 LParl). Calendrier : audience préliminaire 30.10, mise en accusation potentielle 15.12.2020. Communication immédiate (15 octobre) avant publication DélCdG : 'le MPC mène une instruction pénale indépendante du processus parlementaire'.",
            # Distracteur 2 : position dilatoire
            " Justification : la séparation des pouvoirs impose au MPC de ne pas se substituer à la haute surveillance parlementaire pendant qu'elle est en cours. Le calendrier optimal : laisser la DélCdG finaliser son rapport (10 novembre 2020), prendre connaissance des conclusions parlementaires, puis décider en connaissance de cause si une procédure pénale est opportune ou non. Communication publique brève : 'le MPC examinera les conclusions DélCdG et statuera dans un délai approprié'. Sur les demandes étrangères : renvoi pur au DFAE avec note interne : 'la position juridique MPC sera communiquée en interne au DFAE dans un délai d'un mois'. Réunions hebdomadaires de coordination tenues mais sans décision active jusqu'au 15 novembre. Calendrier global : décision finale MPC repoussée à T1 2021 (vs mi-2021 dans la stratégie active)."
        ],
        # Step 3 — décision finale
        3: [
            # Distracteur 1 : mise en accusation
            " Plan d'accusation détaillé : 3 anciens dirigeants Crypto AG identifiables sur la période 2010-2018 (CEO, CTO, Compliance Officer) + 2 anciens collaborateurs SRC stratégique (chef opérationnel 2010-2015 + son successeur 2015-2018). Chefs cumulatifs : art. 273 CP (renseignement éco au profit de la CIA-NSA), art. 271 CP (actes pour État étranger sur sol CH), art. 14 LCB (exportations non conformes aux licences SECO post-1996). Renvoi devant le Tribunal pénal fédéral (TPF) à Bellinzone, formation à 3 juges. Calendrier : acte d'accusation mai 2021, audience préliminaire septembre 2021, procès principal printemps-été 2022. Communication MPC : conférence de presse annonçant le procès historique 'Crypto AG / Rubikon'. Pari : un procès public, même s'il aboutit à des acquittements partiels, ferait office d'audit institutionnel complet sur 50 ans de relations CH-CIA-BND.",
            # Distracteur 2 : ordonnance pénale
            " Plan détaillé : ordonnance pénale art. 352 CPP imposant peine pécuniaire à 3 anciens dirigeants Crypto AG identifiables (180 jours-amende à CHF 3'000 = CHF 540'000 par personne, total CHF 1.62M). Chefs : art. 14 LCB + art. 273 CP. Notification individuelle par recommandée avec accusé de réception. Communication publique simultanée le jour J : conférence de presse fedpol-MPC annonçant 'l'épilogue judiciaire de l'affaire Crypto AG', avec noms et fonctions des sanctionnés. Calcul stratégique : (1) les 3 personnes sanctionnées sont âgées 68-79 ans, peu enclines à un procès public médiatique ; (2) leurs avocats les conseilleront probablement de payer pour éviter exposition ; (3) la sanction pécuniaire reste modeste par rapport à leurs fortunes (estimées CHF 8-25M chacun), donc soutenable financièrement ; (4) l'effet politique d'une condamnation rapide est massif. Délai d'opposition art. 354 CPP : 10 jours."
        ]
    },
    
    # ═══════════════ SWISS LIFE / VADIAN ═══════════════
    "swisslife-vadian-supply-chain-pensionskassen-2025": {
        # Step 0 — notification
        0: [
            # Distracteur 1 : notification minimale
            " Argumentaire détaillé : la doctrine PFPDT 2024 admet une marge d'appréciation sur le 'risque pour les personnes concernées' (art. 24 al. 2 LPD). Pour des données limitées à numéros mobile + noms (pas de salaires, pas de données de prévoyance, pas d'adresses), Swiss Life évalue le risque comme modéré et différable. Plan : (A) **PFPDT** : notification standard 72h, formulaire en ligne, contenu factuel court (faits, période 15-21.02, données affectées, mesures correctives). (B) **FINMA** : marge d'appréciation circ. 2023/1 — 'caractère matériel non avéré' compte tenu de l'absence d'impact financier ou opérationnel sur Swiss Life Pension Services. (C) **60 caisses** : notification groupée e-mail simple sur la liste de distribution Swiss Life Pension Services, FAQ en annexe, projet de communication non fourni (les caisses sont autonomes art. 49 LPP). (D) **Assurés** : pas de notification individuelle initiale. Surveillance des plaintes ultérieures via le centre d'appels Swiss Life. Communication publique : communiqué de presse minimaliste lundi 10h00 'incident chez un partenaire technique, données sensibles non affectées'.",
            # Distracteur 2 : dilatoire
            " Argumentaire détaillé : la sous-estimation initiale est doctrinalement justifiable — Swiss Life argumente avoir besoin de plus de temps pour 'qualifier précisément l'incident' avant toute notification, en particulier pour vérifier l'ampleur exacte et l'exhaustivité de la liste d'assurés affectés. Plan : (A) **PFPDT** : notification reportée d'une semaine (au-delà 72h), mémorandum justificatif invoquant 'complexité technique' et 'protection des personnes concernées contre une notification prématurée et alarmiste'. (B) **FINMA** : interprétation interne 'caractère non matériel' selon analyse risques Swiss Life Pension Services. (C) **60 caisses** : notification reportée d'un mois pour 'éviter la panique chez les conseils de fondation' et permettre à Swiss Life de proposer un plan de remédiation complet en même temps. (D) **Assurés** : pas de notification individuelle, communication uniquement via bandeau d'information sur le portail Swiss Life Pension Services (visible lors de la connexion). Stratégie globale : minimiser couverture médiatique, gérer l'incident en interne via cellule de crise Swiss Life Group, ne communiquer publiquement que si la presse révèle l'incident."
        ],
        # Step 1 — forensique chez Vadian
        1: [
            # Distracteur 1 : focus identitaire seul
            " Plan détaillé : focus exclusif sur l'axe identitaire (piste 1 — compromission credentials). Méthode : (a) extraction logs Azure AD Vadian sur fenêtre 11.02-25.02.2025 (3 semaines), analyse des authentifications anormales (géo-localisation hors UE/CH, horaires nuit, MFA bypass), identification des comptes service privilégiés (~25 comptes IAM Vadian). (b) Vérification credentials Vadian sur HIBP (Have I Been Pwned) + scan rapide GitHub via Google dorks. (c) Hypothèse de travail : compromission classique d'un compte service via réutilisation de mot de passe ou phishing employé. Pas d'audit code source de l'API SMS 2FA (jugé hors scope, ressources limitées). Pas d'analyse NetFlow ni PCAP (volume jugé trop important, économie de temps de 4-5 jours). Pas d'interviews employés Vadian (suspecter un insider générerait des tensions internes contre-productives). Mandat exclusif à l'équipe OFCS interne (8 ingénieurs forensiques), sans expertise externe Compass Security ou Kudelski. Rapport en 5 jours ouvrables (vs 10 dans plan complet). Coût estimé : CHF 95'000 (vs CHF 280'000 plan complet).",
            # Distracteur 2 : Mandiant transparence
            " Plan détaillé : consortium international d'experts pour transparence radicale et contribution communautaire. (A) **Composition** : Mandiant (Google Cloud Security, équipe APT investigation, lead) + CrowdStrike (Falcon Intelligence team) + Trellix (FireEye héritage). Budget consortium CHF 650'000. (B) **Méthodologie** : analyse complète multi-couches sur infrastructure Vadian, accès direct à tous les logs et systèmes, hébergement temporaire des copies forensique chez Mandiant Reston VA pour analyse distribuée. (C) **Publication** : rapport in extenso (~80 pages) avec tous les éléments techniques — logs anonymisés sur identités personnelles mais entiers sur architecture, scripts attaquants reverse-engineered, IOCs détaillés, timeline minute par minute, hypothèses sur l'attribution (TTP comparison avec groupes connus). (D) **Communication** : publications progressives sur site OFCS dédié (un livrable par semaine pendant 8 semaines), conférences techniques sur la plateforme OFCS Talks. Observateurs autorisés : représentants ENISA + BSI (Allemagne) + ANSSI (France). OFCS en rôle d'observateur, coordination directe Vadian-Mandiant. Objectif : démontrer la maturité CH en réponse à incident, partager les leçons avec la communauté cyber CH/UE/internationale, restaurer la réputation Swiss Life par la transparence."
        ],
        # Step 2 — notification assurés / FINMA / MPZH
        2: [
            # Distracteur 1 : minimale
            " Plan détaillé : approche conformité minimale avec économie de ressources. (A) **Notification 13'247 assurés** : envoi par e-mail standard uniquement (économie CHF 32'000 vs courrier postal recommandé), contenu bref 2 pages (faits, mesures correctives, recommandations génériques), pas de hotline 24/7 (renvoi à la FAQ Swiss Life Pension Services et au standard téléphonique régulier 08h-17h ouvrable). (B) **FINMA** : transmission du rapport technique complet OFCS tel quel, sans anonymisation art. 162 CP (jugée superflue car FINMA est autorité publique liée au secret de fonction). (C) **MPZH** : transmission des éléments forensiques sans mandat formel art. 184 CPP (le mandat formel sera demandé ultérieurement si une procédure pénale aboutit). Pas de commission rogatoire Russie envoyée (jugée inutile administrativement vu la non-coopération russe depuis 2022). Pas de notice rouge Interpol demandée (procédure considérée comme prématurée à ce stade). Calendrier : opérations terminées en J+45 (vs J+90 plan complet). Économie totale : CHF 145'000 sur le budget incident.",
            # Distracteur 2 : évitement
            " Plan détaillé : approche défensive avec notification ciblée et minimisation médiatique. (A) **Notification 'différée et ciblée'** : Swiss Life applique un scoring interne de risque sur les 13'247 assurés concernés (algorithme basé sur : montant accumulé sur le portail, fréquence de connexion, données de prévoyance sensibles, indices de vulnérabilité comme personnes âgées ou retraités proches). Identification de ~3'000 assurés à 'risque élevé' qui recevront notification individuelle complète (courrier + e-mail + hotline) ; les ~10'000 autres recevront un message générique sur le portail sans détail sur la nature de l'incident. (B) **FINMA** : refus de transmettre le rapport technique en invoquant art. 50 al. 2 LPD (secret de fonction limitatif applicable aux échanges inter-autorités). Communication FINMA : 'l'incident sera traité dans le cadre du dialogue annuel de surveillance prudentielle Swiss Life'. (C) **MPZH** : aucune transmission, considérant que l'affaire 'reste administrative au PFPDT', pas de procédure pénale à engager à ce stade. Communication publique : conférence de presse Swiss Life mardi présentant l'incident comme 'maîtrisé, clos, sans conséquence pour les assurés'."
        ],
        # Step 3 — rapport doctrinal final
        3: [
            # Distracteur 1 : rapport interne bref
            " Plan détaillé : rapport interne OFCS uniquement, format opérationnel concis. (A) **Diffusion** : rapport interne 15 pages, classification 'OFCS-INTERNAL', accès limité aux ~120 collaborateurs OFCS + 40 référents fedpol cyber + Service de renseignement (SRC division cyber). Pas de partage PFPDT ni FINMA pour 'préserver indépendance institutionnelle'. (B) **Contenu** : (i) chronologie de l'incident 15.02.2025-21.04.2025, (ii) vecteur identifié (credentials exposés GitHub), (iii) recommandations techniques génériques pour fournisseurs IT critiques (rotation secrets, monitoring credentials, audit ISO 27001), (iv) leçons internes OFCS (amélioration processus de réception notifications fournisseurs). (C) **Pas de formation continue** ISP/HSG/UniLU. Pas d'annexe technique anonymisée publiable. (D) **Justification doctrinale** : 'éviter de signaler aux marketplaces criminelles et aux groupes APT les méthodologies de réponse CH, qui pourraient être contournées par des attaquants étudiant les rapports publics'. Position : la doctrine de partage est culturellement anglo-saxonne (FBI, NCA publient beaucoup), la CH conserve sa tradition de discrétion institutionnelle. Calendrier : rapport finalisé décembre 2025.",
            # Distracteur 2 : nouvelle loi
            " Plan détaillé : rapport politique au DDPS/DFJP recommandant nouvelle loi fédérale supply chain cyber LPP en 4 piliers. (1) **Certification obligatoire** : tous les ~150 fournisseurs IT critiques des caisses de pension CH doivent obtenir une certification étatique délivrée par une nouvelle agence à créer (OFCS-Supply-Chain ou ANCS — Agence nationale de certification cyber-financière). Audit annuel par auditeurs accrédités CH (~CHF 35'000-80'000 par audit). (2) **Sanctions** : amende minimum CHF 500'000 par incident supply chain affectant une caisse de pension, doublée si récidive, triplée si défaut de notification. Sanctions complémentaires : interdiction d'exercice professionnel 3-5 ans pour CISO en cas de faute grave. (3) **Souveraineté** : interdiction d'utiliser des fournisseurs hors CH pour les caisses de pension publiques (cantonales, communales) et les fondations collectives de plus de 5'000 assurés. Liste positive des fournisseurs autorisés mise à jour annuellement par l'OFCS. (4) **Responsabilité pénale** : art. 143bis CP étendu aux CISO en cas d'incident attribuable à négligence de leur fonction de surveillance (présomption simple, renversement de charge). Annonce médiatique de la proposition de loi le 15 octobre 2025 lors d'un colloque OFCS public, avant validation politique par Conseil fédéral et Parlement."
        ]
    },
    
    # ═══════════════ HYDRA ═══════════════
    "hydra-darknet-acheteurs-suisses-bka-2022": {
        # Step 0 — cadrage juridique
        0: [
            # Distracteur 1 : EIMP exclusif
            " Plan détaillé : application stricte EIMP pour garantir validité procédurale absolue. (A) **Demande formelle à ZIT Francfort** : courrier officiel OFJ ⟶ ZIT le 28 avril 2022, requérant dépôt commission rogatoire passive DE→CH formelle avec : (i) identification précise des données demandées (CDR Hydra acheteurs/vendeurs CH), (ii) qualification juridique allemande (art. 29 BtMG + art. 261 StGB), (iii) qualification correspondante CH (double incrimination art. 19 LStup + art. 305bis CP), (iv) engagement de spécialité (art. 67 EIMP). (B) **Examen OFJ** : 4-6 semaines pour décision d'entrée en matière (art. 80a EIMP). (C) **Voie de recours** : délai 30 jours art. 80e EIMP pour les personnes potentiellement concernées (à ce stade non identifiées, recours peu probable). (D) **Transmission formelle** : 2-4 mois après décision OFJ définitive. Délai total : 3-6 mois avant fedpol ne reçoive les données. (E) **Coopération opérationnelle anticipée** : suspendue jusqu'à formalisation EIMP. Justification : éviter toute contestation des preuves au procès suisse, garantir le respect intégral du droit international d'entraide. Communication au BKA : 'la Suisse applique strictement l'EIMP, nous vous remercions de votre patience procédurale'.",
            # Distracteur 2 : informel exclusif
            " Plan détaillé : exploitation maximale du canal opérationnel BKA-fedpol pour rapidité. (A) **Réception** : transmission directe BKA ⟶ fedpol CRD via canal liaison Tobias S. avec chiffrement PGP, sans transit par OFJ. (B) **Distribution rapide** : remise aux 26 procureurs cantonaux dans les 72h via Réseau de communication intercantonal sécurisé (CCJ-NEDIK). Chaque procureur reçoit la liste des acheteurs CH résidents de son canton avec données brutes (pseudonyme Hydra, montants BTC, produits). (C) **Pas de demande EIMP formelle** : économie procédurale jugée significative (3-6 mois gagnés). (D) **Justification doctrinale** : 'le démantèlement Hydra est public, le BKA partage publiquement les informations sur l'opération, donc les utilisateurs ne peuvent invoquer un secret particulier'. Position philosophique : la coopération internationale pratique a précédence sur le formalisme procédural quand l'enjeu est urgent et la coopération bilatérale historique éprouvée. Communication BKA : remerciements et confirmation d'utilisation immédiate. Pas de mention au PFPDT (jugée non requise car données reçues d'autorité homologue étrangère)."
        ],
        # Step 1 — triage MROS/blockchain
        1: [
            # Distracteur 1 : transmission directe NEDIK
            " Plan détaillé : transmission immédiate des données brutes au NEDIK pour répartition cantonale rapide. (A) **Justification** : les 26 procureurs cantonaux et leurs équipes disposent de compétences cyber spécialisées depuis 2020 (formations ISP Neuchâtel, certifications Sleuth Kit, accord cadre Chainalysis canton-by-canton). Le triage initial peut être confié aux cantons selon leurs priorités locales. (B) **Format de transmission** : base PostgreSQL exportée transmise au NEDIK (Daniel N.) le 27 mai 2022 ; le NEDIK assure la répartition aux 14 procureurs principaux (ZH, BE, VD, GE, AG, BS, SG, LU, TI, FR, NE, JU, VS, GR) sous 48h. (C) **Pas de stratification fedpol-MROS** : économie de 6-8 semaines de validation centralisée. Chaque canton applique sa propre méthodologie (certains préfèrent l'ordonnance pénale typée, d'autres l'instruction simplifiée). (D) **Pas de validation blockchain centrale** : Chainalysis et TRM Labs sont déjà sous contrat-cadre avec plusieurs cantons (ZH, GE), qui peuvent valider eux-mêmes. (E) **Identification nominative** : laissée à la diligence de chaque canton via leurs procédures art. 9 LBA habituelles avec les exchanges KYC (Bitstamp CH, Bity SA, Kraken Switzerland). Calendrier : transmission J+30, premières actions cantonales J+45-60.",
            # Distracteur 2 : perquisitions massives
            " Plan détaillé : opération coordonnée d'envergure pour effet dissuasif maximal. (A) **Force de frappe** : 2'500 perquisitions simultanées planifiées sur 24h, le 27 mai 2022 à 06h00 dans les 26 cantons. Coordination fedpol nationale via centre de commandement Berne. Renforts intercantonaux mobilisés (DIVPOL, CCPCS). (B) **Cibles** : 2'400 acheteurs CH identifiés (résidents tous cantons selon répartition Hydra) + 47 vendeurs CH. Saisies : matériel informatique, smartphones, supports physiques (drogues conservées), cryptoactifs (wallets identifiés via Chainalysis pré-validation rapide 1 jour). (C) **Communication** : conférence de presse fedpol-MPC le 28 mai à 11h00 annonçant 'l'opération anti-darknet la plus large de l'histoire suisse'. Diffusion liste agrégée par canton et catégorie de produit (cannabis, drogues dures, faux papiers, données volées). (D) **Calendrier accéléré** : préparation logistique 27 avril-25 mai, exécution 27 mai, premières interpellations et auditions dans la foulée, ordonnances pénales typées émises sous 6 semaines. (E) **Justification stratégique** : 'envoyer un signal fort aux utilisateurs darknet en CH — la Suisse n'est plus un refuge', restaurer la crédibilité fedpol après cas WallStreet Market 2019 jugé tiède."
        ],
        # Step 2 — coordination NEDIK / cantons
        2: [
            # Distracteur 1 : cantonalisation pure
            " Plan détaillé : application stricte du fédéralisme judiciaire. (A) **Distribution intégrale** : les 2'400 acheteurs CH + 47 vendeurs CH sont répartis aux 14-26 procureurs cantonaux selon le for ordinaire art. 33 CPP (canton de domicile pour les acheteurs, lieu d'expédition pour les vendeurs). Le NEDIK joue un rôle administratif de coordination logistique sans pouvoir directif. (B) **Méthodologies cantonales** : chaque canton applique sa doctrine propre — certains (VD, GE, ZH) ont des départements pénal éco renforcés ; d'autres (FR, JU, NE) traitent moins de cas et appliquent des procédures plus simples ; le TI utilise des modèles italiens (ordonnance contraventionnelle directe). (C) **Pas de modèles d'ordonnance pénale communs** : économie d'effort fedpol, mais chaque canton génère ses propres modèles. Différenciation jurisprudentielle locale possible (amende CHF 100 dans certains cantons, CHF 300 dans d'autres pour cannabis personnel). (D) **Vendeurs CH** : tous traités cantonalement sans saisine MPC art. 23 CPP. Justification : la qualification organisation criminelle art. 260ter CP est rare et difficile à établir, le cantonal est suffisant pour la majorité. (E) **Communication publique** : chaque canton communique indépendamment selon sa pratique (certains nominativement post-jugement, d'autres anonymement, d'autres uniquement chiffres agrégés). Coordination fedpol minimale.",
            # Distracteur 2 : MPC pour tous
            " Plan détaillé : approche centralisée fédérale pour cohérence maximale et qualification organisation criminelle. (A) **Compétence MPC art. 23 CPP** : invocation de l'art. 260ter CP (organisation criminelle) — Hydra étant manifestement une organisation criminelle internationale structurée selon ATF 132 IV 132 (organisation, durée, secret, capacité d'auto-conservation), tous ses utilisateurs (acheteurs comme vendeurs) sont considérés comme parties à l'organisation. Compétence MPC pour les 2'400 + 47 dossiers. (B) **Centralisation à Berne** : MPC mobilise 25 procureurs cyber + 40 analystes pour gérer le flux. Création d'une cellule 'Operation Hydra-CH' dédiée. Budget supplémentaire CHF 8.2M sur 2 ans. (C) **Inculpations en série** : chaque acheteur est prévenu pour 'participation à organisation criminelle' (art. 260ter CP) + infraction de fond LStup. (D) **Communication maximale** : conférence de presse mensuelle MPC annonçant les inculpations, identités nominatives publiées au fur et à mesure pour 'effet dissuasif fort'. Liste publique des prévenus accessible sur site MPC dédié, avec photos et chefs d'accusation. (E) **Justification stratégique** : 'la Suisse doit montrer qu'elle traite le darknet comme criminalité organisée, à l'instar des cartels et des mafias'. Calendrier : inculpations massives entre août 2022 et juin 2023."
        ],
        # Step 3 — rapport doctrinal
        3: [
            # Distracteur 1 : interne fedpol bref
            " Plan détaillé : rapport interne fedpol court (8 pages), classification 'fedpol-INTERNAL', diffusion limitée aux ~600 référents cyber fedpol + cantonaux. (A) **Pas de coordination MPC-MROS-OFJ** pour publication conjointe ; chaque institution publie ses propres bulletins internes si elle le souhaite. (B) **Contenu** : (i) chronologie 5.04.2022-30.09.2023, (ii) volumes (2'400 acheteurs + 47 vendeurs, ~118 instructions, ~5 procédures MPC art. 260ter), (iii) cryptoactifs saisis CHF 4.2M, (iv) leçons opérationnelles internes. (C) **Pas de diffusion publique**, pas de formation continue ISP/UniLU. (D) **Justification** : 'éviter de signaler aux marketplaces darknet futures (Hydra 2, nouveaux entrants estimés 2-3 par an selon rapport Europol 2023) les méthodologies CH de réception, triage, blockchain validation et NEDIK répartition'. Position : la doctrine de discrétion institutionnelle CH est cohérente avec la tradition fedpol depuis sa fondation 1999. Le partage public risque de devenir un guide pour les attaquants étudiant les techniques d'investigation. Calendrier : rapport finalisé octobre 2023, communication purement interne.",
            # Distracteur 2 : loi répressive
            " Plan détaillé : rapport politique au DFJP recommandant nouvelle loi fédérale 'darknet et marketplaces criminelles' en 4 volets. (1) **Sanctions renforcées** : peine privative minimum 6 mois pour TOUT achat sur darknet (indépendamment du produit cannabis ou plus dur), peine privative minimum 2 ans pour vendeur, qualification automatique 'organisation criminelle art. 260ter CP' pour toute transaction marketplace darknet. (2) **Compétence MPC obligatoire** : extension art. 23 CPP à toutes les infractions darknet, sortant définitivement du champ cantonal. Centralisation à Berne. (3) **Interdiction Tor en CH** : filtrage des nœuds Tor par les opérateurs internet CH (Swisscom, Sunrise, Salt, Init7, etc.), application de l'art. 13 LCB par analogie. Sanction art. 292 CP pour utilisateurs récurrents identifiés. (4) **Surveillance FAI** : obligation pour tous les FAI CH de signaler tout client utilisant Tor ou VPN avec exit nodes étrangers, base de données nationale auprès du SRC. Tableau de bord OFCS en temps réel. Communication médiatique de la proposition de loi le 15 décembre 2023 lors d'une conférence de presse OFCS-fedpol-MPC, avec mise en garde publique 'la Suisse durcit sa réponse au darknet'."
        ]
    },
    
    # ═══════════════ LOCKBIT ═══════════════
    # NB : Step 0 distracteur 1 (EIMP standard) déjà étoffé ci-dessus. Reste step 0 distracteur 2 + steps 1, 2, 3.
    "lockbit-cronos-saisie-serveur-tessin-2024": {
        # Step 0 — déjà partiellement traité (le 1er distracteur étoffé manuellement)
        # Maintenant 2e distracteur (Option 3 informel)
        0: [
            # Le 1er distracteur a déjà été étoffé manuellement (Option 2 EIMP standard) — skip
            None,  
            # Distracteur 2 (Option 3 informel pur)
            " Plan détaillé : exploitation maximale du canal opérationnel fedpol-NCA pour rapidité. (A) **Conv. Budapest art. 30** : invocation directe entre fedpol CRD (Joëlle Egger) et NCA Manchester Cybercrime Unit (DCI Whitmore), échange opérationnel d'informations et coordination tactique sans transit par OFJ. (B) **Accord bilatéral fedpol-NCA 2018** : mémorandum d'entente sur la coopération opérationnelle directe entre forces de l'ordre pour les enquêtes urgentes cyber. Précédent : 12 opérations conjointes CH-UK 2019-2023, retours positifs. (C) **Pas de demande EIMP formelle** : jugée trop lente (T-22h) et risque de fuite via canaux diplomatiques. (D) **Pas de saisine TMC** : la coordination informelle Budapest art. 30 est considérée comme couverture juridique suffisante pour saisie de courte durée (saisie + imagerie in situ + restitution dans les 48h). Le datacenter sera informé après l'opération de la base juridique invoquée. (E) **Exécution fedpol** : équipe CRD + Polizia Cantonale Ticino (5 agents cyber) + Compass Security forensique, sur instruction directe NCA. Coordination Europol EC3 informelle (canal téléphonique direct, pas le canal chiffré 'Op-Cronos-EXEC'). (F) **Procédure pénale CH** : différée — ouverture éventuelle par MPC après finalisation des éléments, pas de procédure préliminaire art. 309 CPP avant la saisie. Communication publique : aucune avant 20.02 11h30 GMT (annonce internationale). Justification : 'la rapidité prime sur le formalisme dans les opérations cyber urgentes'."
        ],
        # Step 1 — mobilisation TMC + Polizia Cantonale TI + Compass
        1: [
            # Distracteur 1 : minimaliste
            " Plan détaillé : mobilisation économique pour optimisation budget urgence. (A) **Saisine TMC par téléphone seul** : appel à Me Karin Inglin (TMC Berne) lundi 06h00 ; argumentaire oral 15-20 minutes sur l'urgence Operation Cronos, sans dossier écrit préalable (à fournir post-décision sous 48h). Pari : Me Inglin acceptera l'urgence Sunday-Monday week-end et signera oralement, écrit par la suite. (B) **Mobilisation Polizia Cantonale TI** : 2 agents cyber spécialisés cellule Lugano (économie sur les 5-7 prévus dans plan complet ; les autres restent disponibles pour leurs dossiers en cours). Pas de patrouille de sécurité dédiée (le datacenter est privé, accès supposé sans résistance). (C) **Compass Security** : 1 expert forensique senior (au lieu de 4) — équipement réduit : 2 HDD vierges 20 TB, 1 hub Tableau TX1, write-blockers. Mandat formel art. 184 CPP signé MPC. (D) **Coordination NCA** : appels téléphoniques bilatéraux directs DCI Whitmore ⟷ Egger pendant la journée de lundi, pas de canal Europol EC3 commun (jugé bureaucratique). (E) **Calendrier déploiement** : pré-positionnement Lugano à 19h00 (2h avant H-Hour) — gain de 2h par rapport au plan 17h00 plus prudent. Briefing rapide sur place. Économie totale : ~CHF 85'000 sur le budget opération + 6 agents-jours mobilisés ailleurs.",
            # Distracteur 2 : force démesurée
            " Plan détaillé : déploiement massif pour neutralisation tactique et effet de levier. (A) **Effectifs** : 30 agents armés cumulés (15 fedpol CRD + 8 Polizia Cantonale Ticino spécialisés + 7 patrouille intervention CH). Équipement tactique : armures pare-balles, taser, fusils d'assaut SIG 553, équipement de tir non-létal. Hélicoptère Air-Glaciers en standby Lugano-Agno (15 min de vol) avec équipe d'intervention spéciale renforcée si nécessaire. (B) **Blocage des routes** : 4 patrouilles bloquent les routes d'accès principales (Via San Salvatore, autoroute A2 sortie Lugano-Sud) dès 18h00 CET, soit 2h avant H-Hour. (C) **Perquisition simultanée domicile** : équipes secondaires (3 par foyer) interviennent au domicile des 3 dirigeants identifiés du datacenter X-Datacenter SA (CEO, CTO, COO) à 21h00 CET exactement, pour interrogatoire immédiat et saisie matériel domestique. (D) **Communication médiatique simultanée** : conférence de presse fedpol-Polizia Cantonale TI à 21h30 CET (30 min après début saisie) annonçant l'opération en cours pour 'effet de levier maximal sur LockBit et les hébergeurs complaisants'. Présence de journalistes invités sur le périmètre à distance. (E) **Forensique** : pas d'imagerie in situ (jugée trop lente, 6-8h chacune sur les 4 racks). Saisie physique de tous les serveurs (~120 kg équipement), transport sous escorte fedpol à Berne le 19.02-20.02 nuit pour analyse en lab. Justification : 'sécurité optimale, contrôle total de la chaîne de garde'."
        ],
        # Step 2 — exécution saisie 20h00 GMT
        2: [
            # Distracteur 1 : pas de capture RAM
            " Plan détaillé : exécution simplifiée prioritaire 'no-wipe'. (1) **20h00 GMT exact** : entrée fedpol CRD + Polizia Cantonale TI dans le datacenter X-Datacenter SA, présentation mandat TMC, sécurisation salle serveurs cible. Les 12 employés présents sont regroupés en salle de pause sous surveillance, sans saisie d'objets personnels, interdiction téléphone 4h. (2) **20h02 GMT** : équipe Compass Security entre, identification physique des 4 racks LockBit (selon liste NCA — adresses MAC, numéros de série fournis par renseignement NCA). (3) **20h05 GMT** : déconnexion immédiate réseau des 4 racks (priorité absolue : empêcher wipe distant déclenché par LockBit ayant détecté les saisies des autres pays). Débranchement Ethernet, isolation totale du switch upstream. (4) **20h10-22h00 GMT** : imagerie forensique disques bit-by-bit (~80-120 TB cumulés) avec hub Tableau TX1 + write-blockers. Pour chaque disque : hash SHA-256 avant/après, double copie. Pas de capture RAM volatile (jugée non prioritaire et risque-augmentation : laisser le serveur fonctionner pendant capture RAM = délai supplémentaire pendant lequel LockBit peut wiper). (5) **22h00-22h30 GMT** : scellage physique art. 248 CPP des disques originaux + procès-verbal. (6) **22h30 GMT** : levée dispositif. Communication aux 12 employés : pas d'instruction explicite sur le secret de l'enquête (jugée superflue car les annonces internationales se feront le lendemain matin de toute façon).",
            # Distracteur 2 : refus de confirmer READY
            " Plan détaillé : application du principe de précaution maximale à T-1 min. (A) **À 19h59 GMT** : vous décidez de ne PAS confirmer READY à Europol EC3 et de demander un délai supplémentaire de 30 minutes 'pour vérifier un détail juridique procédural' (l'élément précis n'est pas identifié, c'est une mesure de prudence générique sur la chaîne MPC-OFJ-TMC-fedpol-Polizia Cantonale-Compass Security). (B) **Communication EC3** : message officiel à Mme Anke V. (europol_ec3_liaison) demandant report du H-Hour pour CHE-LUG-01 à 20h30 GMT. (C) **Argumentaire** : 'la doctrine procédurale suisse exige une vérification finale rigoureuse avant exécution irréversible. Le principe de précaution prime sur la synchronisation tactique. 30 minutes supplémentaires permettront de vérifier la chaîne mandat TMC → procédure préliminaire MPC → autorisation EIMP OFJ → exécution sur le terrain. La Suisse ne peut pas prendre le risque d'une saisie ultérieurement annulée par le TPF.' (D) **Options pour EC3** : (i) reporter le H-Hour multilatéral de 30 min pour synchronisation (re-coordination des 8 pays), ou (ii) maintenir le H-Hour 20h00 GMT et exécuter sans CH (perte du serveur LockBit en CH). EC3 doit décider en moins de 30 secondes. (E) **Justification philosophique** : 'la prudence suisse est notre marque de fabrique institutionnelle ; mieux vaut perdre une opération que d'engager la Confédération dans une procédure contestable'. Conséquences acceptées par avance : retard de communication internationale, potentiel mécontentement NCA, mais souveraineté juridique CH préservée."
        ],
        # Step 3 — communication finale
        3: [
            # Distracteur 1 : minimal
            " Plan détaillé : approche communicationnelle économique post-opération. (A) **Communication CH** : communiqué de presse écrit fedpol-MPC publié sur site fedpol mardi 12h00 CET (sans conférence de presse en présentiel). Contenu factuel court (8 lignes) : 'La Suisse a participé à l'Operation Cronos contre LockBit. Une saisie a été effectuée sur sol suisse en coopération avec la NCA britannique. L'enquête se poursuit.' Pas de mention du datacenter tessinois (procédure en cours). Pas d'annonce des 47 victimes CH identifiées. Communication monolingue allemand-français (pas de version italienne ni anglaise). (B) **Procédure pénale CH parallèle** : MPC ouvre procédure préliminaire art. 309 CPP limitée aux chefs art. 143bis CP (accès indu) + art. 144bis CP (détérioration de données) — pas d'art. 305bis CP (blanchiment) ni art. 260ter CP (organisation criminelle), jugés 'trop ambitieux à ce stade'. Procédure contre les administrateurs LockBit (inconnus) uniquement, pas contre le datacenter (jugé probablement de bonne foi). (C) **47 victimes CH** : pas de contact individuel par fedpol — les victimes peuvent se signaler spontanément si elles souhaitent assistance ou information sur les clés de déchiffrement Europol. Programme 'OFCS Cyber Help' non activé spécifiquement pour ce dossier. Calendrier : décisions de classement ou poursuite attendues T2 2024.",
            # Distracteur 2 : maximaliste
            " Plan détaillé : approche communicationnelle offensive pour visibilité internationale CH. (A) **Conférence de presse fedpol-MPC** mardi 11h30 GMT exactement (en concurrence directe avec annonce NCA-Europol simultanée). Présidée par : cheffe fedpol + procureure cyber Furrer + cheffe OFCS Tschanz + commandant Polizia Cantonale TI. Lieu : Palais fédéral Berne, salle des Médias. Diffusion live multilingue FR/DE/IT/EN. (B) **Annonces nominatives** : (i) nom complet du datacenter (X-Datacenter SA Lugano, Via San Salvatore 21) avec photos extérieures du bâtiment, (ii) noms des 3 dirigeants identifiés comme 'soupçonnés de complicité ou de bullet-proof hosting' (CEO, CTO, COO), (iii) liste des 47 victimes CH avec initiales + secteur d'activité + canton de domicile + montant de rançon demandé (anonymisation jugée 'partielle suffisante'). (C) **Mise en accusation immédiate** : les 3 dirigeants datacenter sont prévenus le mardi pour blanchiment d'argent (art. 305bis CP) + organisation criminelle (art. 260ter CP) + complicité ransomware (art. 25 CP + 143bis CP + 144bis CP). Détention provisoire demandée au TMC ZH le mercredi. (D) **Clés de déchiffrement publiques** : publication de toutes les clés Europol récupérées sur site OFCS dédié, téléchargeables par tous sans contact préalable victimes. Justification : 'maximiser l'effet réparateur pour toutes les victimes, y compris non identifiées'. (E) **Effet recherché** : 'asseoir la position CH au premier plan international, démontrer la capacité fedpol-MPC à frapper fort, dissuader les hébergeurs bullet-proof de s'installer en CH'."
        ]
    }
}

# ── Application ──────────────────────────────────────────────────
total_modified = 0
for scene_id, steps_pads in PADDINGS.items():
    path = Path(f'scenes/{scene_id}.json')
    scene = json.loads(path.read_text(encoding='utf-8'))
    modified = 0
    for step_idx, pads in steps_pads.items():
        step = scene['steps'][step_idx]
        # Identifier les distracteurs (non-ok) dans l'ordre où ils apparaissent
        non_ok_indices = [i for i, c in enumerate(step['choices']) if not c.get('ok', False)]
        # Appliquer le padding correspondant à chacun
        for pad_idx, choice_idx in enumerate(non_ok_indices):
            if pad_idx < len(pads) and pads[pad_idx] is not None:
                step['choices'][choice_idx]['text'] += pads[pad_idx]
                modified += 1
    path.write_text(json.dumps(scene, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f"  ✓ {scene_id}: {modified} distracteurs étoffés")
    total_modified += modified

print(f"\nTotal: {total_modified} distracteurs étoffés sur 4 scènes")
