"""Étoffe les 18 distracteurs des 3 scènes Priorité 3 (TikTok, antisémitisme, deepfake EMS)
pour atteindre ratio bon/mauvais < 1.5 (cible < 1.3).

Stratégie identique à pad_distractors_4cas_reels.py : ajouter du détail technique
crédible mais qui ne change pas la nature 'mauvais choix' du distracteur.
"""
import json
from pathlib import Path

PADDINGS = {
    # ═══════════════ TIKTOK / MINEUR-AUTEUR ═══════════════
    "mineur-auteur-defi-tiktok-deces-vd": {
        0: [
            # Distracteur 1 : meurtre art. 111 CP (maximaliste)
            " Justification politique : 'l'opinion publique vaudoise doit voir que la justice protège les enfants contre les dérives TikTok'. (B) **Mesures de protection L.M.** : placement immédiat art. 15 DPMin en institution fermée (Centre Pradervand Yverdon ou Centre des Léchaires Ecublens), interdiction de contact avec la famille K. art. 14 DPMin alinéa 2, interdiction totale d'accès internet/réseaux sociaux pendant 6 mois. (C) **Audition Tribunal des mineurs** : audience publique convoquée dans les 30 jours, sans huis clos malgré art. 4 PPMin (jugé surmontable par dérogation pour intérêt général). (D) **Communication MP-VD** : conférence de presse mardi 13h30 annonçant les chefs d'inculpation et le placement, avec photo anonymisée du Centre Pradervand. (E) **Coordination école** : information du DGEO Vaud (Pascal R.) pour mise en place protocole 'défis dangereux' dans les 13 établissements secondaires du district. Risque de stigmatisation publique de L.M. assumé pour 'effet dissuasif sur autres ados'.",
            # Distracteur 2 : non-entrée en matière (minimaliste)
            " Argumentation détaillée : (a) le défi 'Blackout Challenge' relève d'un phénomène viral mondial dont aucun pays n'a réussi à attribuer pénalement la responsabilité aux co-participants, la causalité juridique entre l'encouragement de L.M. et le décès étant trop ténue pour fonder un homicide par négligence ; (b) L.M. n'avait pas conscience du risque mortel réel (seulement 15 ans, discernement art. 9 DPMin questionnable au sens art. 19 CP), la jurisprudence vaudoise ATF 6B_456/2022 retient l'absence de discernement chez les mineurs face à des défis sociaux ; (c) la procédure pénale risque d'aggraver le trauma de la famille K. en ravivant médiatiquement la cause du décès. Décision : ordonnance de non-entrée en matière art. 310 CPP avec notification courte aux parents victimes. Communication brève à l'école pour gestion psychologique des élèves. Pas de mesure protectrice DPMin contre L.M. (jugée superflue vu l'absence de qualification pénale). Calendrier : décision notifiée J+10, dossier archivé J+30."
        ],
        1: [
            # Distracteur 1 : restrictif maximal (placement fermé)
            " Justification : la gravité du décès et l'exposition médiatique (24heures, RTS, 20 Minutes) imposent une réponse forte de l'autorité. (2) **Expertise pédopsychiatrique SUPEA-CHUV** : mandat limité à l'évaluation de la responsabilité art. 19 DPMin uniquement (capacité de discernement au moment des faits), sans extension aux 4 axes (parcours, trauma, contexte familial, prévention récidive). Économie sur le mandat : CHF 8'500 vs CHF 24'000 plan complet. Délai expertise réduit à 4 semaines (vs 10-12 semaines plan complet). (3) **Communication suite fuite 24heures** : refus de toute communication MP-VD au journaliste Marc V., position 'secret de l'enquête art. 73 CPP, aucun commentaire'. Convocation à l'audition disciplinaire interne de toute personne ayant accès au dossier pour identifier la source de la fuite. Risque que d'autres médias amplifient l'absence de transparence officielle, alimentant les spéculations. (4) **Coordination établissement scolaire** : suspension du protocole 'défis dangereux' DGEO Vaud (jugé prématuré tant que la procédure pénale n'est pas terminée). Absence de cellule d'écoute spécifique dans l'établissement.",
            # Distracteur 2 : permissif total
            " Argumentation détaillée : (a) L.M. n'est qu'un adolescent de 15 ans victime lui-même du phénomène viral TikTok, lui appliquer des mesures restrictives ajouterait un trauma au trauma, contre-productif sur le plan thérapeutique ; (b) le retour rapide au domicile permet de préserver le lien familial et la continuité scolaire (école obligatoire art. 19 Cst. + LEO VD art. 45), élément stabilisateur essentiel ; (c) ne pas demander d'expertise pédopsychiatrique évite la stigmatisation institutionnelle de L.M. et économise les ressources SUPEA-CHUV pour des cas plus graves (~CHF 24'000 économisés). (2) **Communication suite fuite 24heures** : interview accordée à Marc V. par le procureur des mineurs, présentant L.M. comme 'victime des algorithmes TikTok au même titre que le décédé', stratégie de désamorçage médiatique. (3) **Coordination établissement scolaire** : pas de protocole 'défis dangereux' spécifique (jugé alarmiste), simple rappel oral aux enseignants des règles habituelles de surveillance. (4) **Communication parents K.** : message bref de condoléances institutionnelles, sans rencontre formelle avec la procureure (jugée délicate)."
        ],
        2: [
            # Distracteur 1 : restrictif minimaliste (4 co-encourageurs)
            " Justification : économie procédurale et focus sur le dossier principal L.M. (2) **N. (14 ans, encourageur explicite 'oui vas-y t'es pas un lâche')** : examiné comme témoin uniquement, audition art. 162 CPP en présence de ses parents, sans qualification pénale (jugé enfant trop jeune malgré ses 14 ans dépassant l'âge plancher art. 3 DPMin de 10 ans). (3) **TikTok coopération** : demande standard via formulaire EU DSA art. 22 sans recours au canal accéléré DSA art. 16, délai estimé 4-6 semaines (vs 7-10 jours canal accéléré). Justification : 'urgence relative, le mineur décédé ne peut plus être sauvé'. (4) **Action civile parents K.** : pas de soutien proactif MP-VD pour orientation vers conseil juridique pro bono. Famille laissée seule pour évaluer ses options art. 41 CO contre TikTok / contre L.M. / contre N. Communication MP-VD aux parents K. : 'vous pouvez consulter un avocat à vos frais, le ministère public se concentre sur le pénal'.",
            # Distracteur 2 : expansif (tous mis en cause)
            " Justification : effet dissuasif maximal pour 'prévenir la prochaine génération de défis viraux mortels'. (B) **N. (14 ans)** : mis en cause art. 25 CP + art. 117 CP comme co-instigateur principal (son encouragement explicite est jugé causalement décisif), ouverture procédure DPMin séparée avec mêmes mesures qu'L.M. (placement institutionnel art. 15 DPMin). (C) **TikTok coopération** : commission rogatoire EIMP CH→IE déposée immédiatement contre ByteDance Dublin avec demande de blocage immédiat de tous les contenus 'Blackout Challenge' sur le territoire suisse (art. 24 DSA UE 2022/2065 invoqué + art. 47 LCom CH). Menace de sanction art. 292 CP si non-coopération sous 72h. (D) **Action civile parents K.** : MPC-VD constitue partie plaignante d'office au nom des parents (sans leur accord préalable), demande CHF 240'000 par parent en dommages-intérêts contre L.M. et N. (sans considérer l'incapacité financière des familles modestes), action subsidiaire contre TikTok pour CHF 5 millions, action subsidiaire contre l'État de Vaud pour défaut de surveillance scolaire art. 22 LResp."
        ],
        3: [
            # Distracteur 1 : répressif maximal
            " Justification politique : 'la justice vaudoise doit envoyer un signal fort contre les défis TikTok mortels, sanction exemplaire'. (b) **Mesures additionnelles** : retrait de la garde parentale aux parents L.M. pour 'défaut de surveillance grave' (art. 310 CC + art. 35 DPMin), placement L.M. en institution fermée jusqu'à ses 18 ans (1'095 jours). (c) **Communication MP-VD** : publication intégrale du jugement sur le site MPC-VD avec identification anonymisée par initiales 'L.M., 15 ans, VD' (réidentifiable par proches), communiqué officiel multilingue FR/DE/IT/EN diffusé aux médias suisses et internationaux. (d) **Restrictions** : interdiction totale et définitive d'accès aux réseaux sociaux jusqu'à 18 ans (TikTok, Instagram, Snapchat, Discord, Reddit, X, YouTube), surveillance par bracelet électronique art. 8 LMSS pendant 24 mois. (e) **Coordination écoles** : déploiement immédiat protocole DGEO Vaud dans 87 établissements secondaires vaudois, intervention obligatoire SUPEA-CHUV dans chaque classe de niveau 8-11 sur 6 mois. Coût estimé CHF 2.4 millions sur ressources DGEO.",
            # Distracteur 2 : permissif minimaliste
            " Argumentation détaillée : (a) L.M. a déjà subi un trauma majeur en perdant un camarade, lui imposer une sanction supplémentaire serait inhumain et contre-productif sur le plan psychologique ; (b) la réprimande art. 21 DPMin est la sanction la plus douce du dispositif suisse, parfaitement adaptée aux mineurs présentant un risque de récidive très faible ; (c) le suivi psychothérapeutique relève de la sphère privée familiale, l'imposition judiciaire (art. 14 DPMin) serait paternaliste. (2) **Pas de communication anonymisée publique** : éviter toute exposition médiatique, même anonymisée, de L.M. et de sa famille. Position : 'l'affaire ne concerne que la famille K. (victimes) et la famille L.M. (auteurs), pas le public'. (3) **Restrictions** : aucune restriction d'accès aux réseaux sociaux (jugée disproportionnée), pas de bracelet électronique. (4) **Coordination DGEO Vaud** : pas de protocole spécifique 'défis dangereux' dans les 87 établissements vaudois (jugé alarmiste et coûteux). Simple courrier rappel aux directeurs sur la vigilance générale. Communication parents K. : ordre du jugement transmis par courrier postal recommandé, sans rencontre."
        ]
    },
    
    # ═══════════════ ANTISÉMITISME 261BIS ═══════════════
    "antisemitisme-ligne-261bis-zh": {
        0: [
            # Distracteur 1 : tout art. 261bis CP (maximaliste)
            " Justification : la stratégie 'tolérance zéro' contre l'antisémitisme post-7 octobre 2023 impose une qualification large pour 'envoyer un signal politique fort à la communauté juive'. (B) **Procédure** : ouverture immédiate d'instruction formelle art. 311 CPP (pas de procédure préliminaire art. 309 CPP) contre 47 inconnus, mandat d'enquête international Interpol notice rouge pour les 17 inconnus identifiés comme résidant à l'étranger (Israël, France, États-Unis). (C) **Communication** : conférence de presse MPZH-FSCI-GRA mardi 11h00 annonçant 'l'ouverture de la plus large enquête antisémite de l'histoire suisse', avec présentation des 47 contenus à l'écran (sans floutage). (D) **Critères ignorés** : pas de distinction entre critique politique légitime d'Israël (Cst. art. 16 liberté d'expression + ATF 148 IV 188 critère du contenu antisémite vs critique gouvernementale), incitation à la haine contre les Juifs comme groupe, et menaces individuelles contre rabbin David R. (E) **Coordination CFR/EKR** : information formelle de Mme Ursula E. (cfr_eckert_president) mais sans solliciter son avis préalable sur la qualification (jugé superflu vu l'évidence).",
            # Distracteur 2 : restrictif (6 menaces de mort seulement)
            " Argumentation détaillée : (a) la liberté d'expression art. 16 Cst. et art. 10 CEDH prime sur l'art. 261bis CP en cas de critique politique du gouvernement israélien, et la grande majorité des 47 contenus relèvent de la critique politique post-7 octobre 2023 et non de l'incitation à la haine raciale ; (b) la jurisprudence TF 6B_627/2015 (UDC Tweet 'Nuit de Cristal') a confirmé que seuls les contenus appelant explicitement à la violence ou niant la Shoah relèvent de l'art. 261bis CP, les autres relevant du débat démocratique ; (c) qualifier les 47 contenus comme antisémites risquerait de stigmatiser des critiques politiques légitimes et d'alimenter un sentiment de 'criminalisation de la critique d'Israël' contre-productif pour la cohésion sociale. (B) **Procédure** : seules 6 affaires individuelles ouvertes (auteurs identifiables des menaces de mort explicites), classement intégral des 41 autres contenus par décision de non-entrée en matière art. 310 CPP. (C) **Communication FSCI-GRA** : courrier formel expliquant la qualification, refus de toute conférence de presse jugée 'instrumentalisante'."
        ],
        1: [
            # Distracteur 1 : informel rapide (manque garanties)
            " Justification : la rapidité est essentielle face à la propagation virale, le formalisme EIMP fait perdre 4-6 semaines précieuses pendant lesquelles les contenus continuent à diffuser haine et menaces. (B) **X (12 contenus)** : demande informelle via le formulaire 'Trust & Safety' grand public de X Corp (formulaire web standard accessible à tout citoyen), sans commission rogatoire formelle. Pas de mandat art. 269ter CPP. Réponse attendue : suppression sous 24-48h selon ToS X mais aucune transmission d'IPs ni de métadonnées (X ne coopère pas sans formalisation CR). (C) **Telegram (29 contenus)** : email standard à abuse@telegram.org (adresse publique), demandant suppression des canaux antisémites identifiés. Pas de canal liaison Europol (jugé bureaucratique). Aucune commission rogatoire EIMP CH→Saint-Vincent (jugée inutile vu la non-coopération historique Telegram). (D) **Identification auteurs CH** : limitée aux profils ayant publié sans VPN ni Tor (~3 auteurs sur 47 contenus). Pour les autres, abandon de l'identification. (E) **Calendrier** : résultats partiels dans 3-4 semaines, mais sans valeur probante recevable au procès art. 141 CPP.",
            # Distracteur 2 : maximaliste avec sanctions diplomatiques
            " Justification politique : 'la Suisse doit montrer aux GAFAM qu'elle ne tolère plus leur laxisme face à l'antisémitisme post-7 octobre 2023'. (B) **Meta** : commission rogatoire EIMP CH→IE Dublin avec en parallèle plainte formelle DG-CONNECT UE pour violation art. 16 DSA UE 2022/2065, demande de sanction administrative jusqu'à 6% du CA mondial Meta (~5.3 milliards EUR). (C) **X Corp** : commission rogatoire EIMP CH→US (San Francisco) avec menace de blocage géographique de X sur le territoire suisse par OFCOM si non-coopération sous 30 jours (art. 6 LRTV par analogie + art. 47 LCom invoqués). (D) **Telegram** : commission rogatoire EIMP CH→Saint-Vincent + Russie (siège opérationnel allégué Dubai/Moscou), menace de désignation Telegram comme 'organisation criminelle complice' au sens art. 260ter CP. (E) **Coordination UE** : convocation des ambassadeurs IE, US, AE par DFAE pour faire pression diplomatique. (F) **Communication médiatique** : conférence de presse MPZH-FSCI-GRA annonçant 'l'offensive judiciaire suisse contre les plateformes complices d'antisémitisme'. Risque réception internationale CH 'pays autoritaire numérique' assumé."
        ],
        2: [
            # Distracteur 1 : restrictif (pas de POPS)
            " Argumentation détaillée : (a) l'art. 28b CC suppose une menace concrète et individualisée, les menaces de mort en ligne sont anonymes et virtuelles, pas de risque physique concret démontré ; (b) ordonner POPS contre 11 auteurs serait disproportionné art. 197 CPP vu l'absence de passage à l'acte ; (c) le rabbin David R. dispose déjà d'une sécurité communautaire ICZ pour les offices, intervention sécurité publique superflue. (2) **Instruction formelle** : limitée aux 6 auteurs des menaces de mort explicites, classement art. 310 CPP des 5 autres (jugés relevant de la critique politique). (3) **Expertise extrême-droite** : pas de mandat Damir S. ZHAW Winterthur (jugé politiquement orienté), MPZH s'appuie uniquement sur son analyse interne. (4) **Coopération CFR/EKR** : information formelle mais sans solliciter d'amicus curiae (jugé alourdissant la procédure). (5) **Communication rabbin** : courrier formel notifiant l'ouverture d'instruction sans rencontre personnelle (procureure trop occupée).",
            # Distracteur 2 : maximaliste répressif
            " Justification politique : 'face à la montée de l'antisémitisme post-7 octobre 2023 (+30% incidents CH selon FSCI), la justice doit frapper fort'. (2) **Arrestation préventive** : 5 des 11 auteurs identifiés comme 'récidivistes potentiels' sont arrêtés à l'aube par Kapo ZH Hass-Kriminalität (Jürg B.), détention provisoire art. 220 CPP demandée au TMC sur la base d'un 'risque concret de récidive' (sans éléments individualisés solides). (3) **Mise en accusation accélérée** : sans phase d'audition contradictoire art. 158 CPP préalable, dépôt d'acte d'accusation directe TPF ZH avec demande peine privative ferme 12-24 mois pour tous les 11 auteurs (sans considérer leur situation individuelle). (4) **POPS étendu** : ordonnance art. 28b CC contre les 11 auteurs ET contre leurs cercles familiaux (frères, parents, conjoints) pour 'éviter contournement par tiers'. (5) **Communication maximale** : conférence de presse MPZH-Kapo-FSCI-GRA-CFR-rabbin lundi 14h00 avec photos arrestation, présentation 'opération anti-antisémitisme la plus large jamais menée en CH'."
        ],
        3: [
            # Distracteur 1 : interne MPZH bref
            " Plan détaillé : rapport interne MPZH 12 pages, classification 'MPZH-INTERNAL', diffusion limitée aux 28 procureurs MPZH + 8 procureurs cantonaux AG-SH (pour cohérence inter-cantonale). Pas de coordination GRA-FSCI-CFR pour publication conjointe. (A) **Contenu** : (i) chronologie 7.10.2023-15.12.2024 ; (ii) volumes (47 contenus, 11 auteurs CH, 12 procédures, 8 condamnations, 3 acquittements) ; (iii) jurisprudence appliquée (ATF 148 IV 188, TF 6B_986/2017) ; (iv) leçons opérationnelles internes MPZH (méthodologie de qualification fine). (B) **Pas de publication GRA** ni FSCI ni CFR/EKR (jugée 'instrumentalisation politique' par communautés religieuses). (C) **Pas de formation continue Université de Bâle ni HSG ni UniLU**. (D) **Justification doctrinale** : 'éviter de donner aux groupes antisémites organisés (extrême-droite, islamistes radicaux) la méthodologie d'investigation CH qui pourrait être contournée'. La doctrine de discrétion institutionnelle MPZH est cohérente avec la tradition cantonale. Calendrier : rapport finalisé janvier 2025, communication purement interne. Pas d'annexe technique anonymisée publiable.",
            # Distracteur 2 : nouvelle loi pénale
            " Plan détaillé : rapport politique au DFJP recommandant nouvelle loi pénale fédérale 'antisémitisme et discriminations en ligne' en 5 piliers. (1) **Investigation sans seuil** : qualification automatique art. 261bis CP pour TOUT contenu mentionnant Israël/Juifs/sionisme dans un contexte critique, indépendamment de la qualification individualisée actuelle (ATF 148 IV 188 jugé 'trop permissif'). (2) **Sanctions renforcées** : peine privative minimum 6 mois pour propos antisémite simple, 12 mois pour partage de contenu antisémite avec plus de 100 vues, 24 mois pour création de contenu, 36 mois pour récidive. (3) **Blocage administratif** : OFCOM autorisé à ordonner le blocage géographique CH de toute plateforme refusant de coopérer sous 48h (X, Telegram, plateformes alternative tech russes). (4) **Surveillance de masse** : obligation pour les FAI CH de filtrer les contenus antisémites par analyse de mots-clés, transmission automatique au SRC + Kapo Hass-Kriminalität. (5) **Compétence MPC obligatoire** : extension art. 23 CPP à toute infraction art. 261bis CP transcantonale, sortant définitivement du champ cantonal. Annonce médiatique de la proposition de loi mardi 11h00 lors de conférence de presse MPZH-FSCI-GRA, avant validation politique."
        ]
    },
    
    # ═══════════════ EMS DEEPFAKE LUCERNE ═══════════════
    "ems-fraude-deepfake-vocal-fils-lu": {
        0: [
            # Distracteur 1 : cadrage minimal
            " Argumentation détaillée : (a) le dossier est techniquement complexe (deepfake vocal, blanchiment, mule, cryptoactifs), il faut éviter d'ouvrir trop de fronts simultanés et concentrer les ressources MPC LU sur l'élément central (l'escroquerie) ; (b) art. 305bis CP contre la mule L.K. peut être ajouté ultérieurement quand son rôle sera plus clairement établi par les investigations ; (c) art. 28 CC contre auteur deepfake pour atteinte à la voix de Stefan H. relève du civil, pas du pénal (séparation des compétences). (B) **APEA/KESB Luzern Nord** : pas de saisine art. 443 CC immédiate (jugée prématurée vu que Maria H., 84 ans, semble lucide et autonome dans ses décisions), simple courrier d'information à la curatrice administrative existante. (C) **Pro Senectute Luzern** : pas de signalement au référent Hans-Peter F. (jugé superflu, l'affaire est judiciarisée). (D) **Communication EMS Sankt-Niklausen** : courrier de la direction à Verena H. demandant simplement la confirmation que Maria H. est protégée par la cellule sociale interne EMS, sans mesure spécifique. Communication MPC LU à la famille H. : courrier standard d'ouverture de procédure pénale, sans rencontre. Calendrier : décisions intermédiaires attendues T2 2024.",
            # Distracteur 2 : maximal médiatique
            " Justification politique : 'lutter contre les arnaques aux deepfake vocal contre les seniors est une priorité, la Suisse doit communiquer fortement'. (B) **APEA/KESB Luzern Nord** : signalement art. 443 CC + demande de mise sous curatelle complète art. 398 CC pour Mme Maria H. (sans considérer son autonomie résiduelle), justification : 'vulnérabilité avérée par la fraude réussie'. (C) **Pro Senectute** : convocation immédiate de Hans-Peter F. pour audition prévenue art. 162 CPP comme co-responsable institutionnel du défaut de prévention (sans qualification pénale claire). (D) **Communication EMS Sankt-Niklausen** : intervention de fedpol PJF avec saisie des téléphones personnels des 89 résidents pour 'vérification d'autres cas similaires non détectés'. (E) **Communication médiatique** : conférence de presse MPC LU-fedpol-Pro Senectute mercredi 10h00 (J+2) annonçant 'l'opération anti-deepfake la plus large jamais menée contre les arnaques aux seniors en Suisse', avec présentation publique du cas Maria H. (anonymisée par initiales 'M.H., 84 ans, EMS Sankt-Niklausen'). Diffusion internationale FR/DE/IT/EN. Risque atteinte sphère privée Maria H. assumé pour 'effet préventif'."
        ],
        1: [
            # Distracteur 1 : recovery uniquement
            " Argumentation détaillée : (a) la priorité absolue est de restituer rapidement les CHF 4'500 récupérés à Mme Maria H. pour limiter son préjudice et préserver sa confiance dans le système bancaire et judiciaire ; (b) la forensique vocal est techniquement utile mais coûteuse (CHF 18'000 mandat Compass Security) et improbablement décisive sans identification préalable de l'auteur deepfake ; (c) l'audition de la mule L.K. peut être différée car elle ne dispose probablement pas des informations sur le commanditaire (architecture de protection typique des réseaux deepfake russophones). (B) **Pas de mandat Compass Security** : décision de différer la forensique vocal jusqu'à identification effective de l'auteur deepfake (calendrier indéterminé). Économie CHF 18'000 sur le budget incident. (C) **L.K. audition** : programmée à 6 semaines (vs J+12 plan complet) pour laisser à son avocat le temps de préparer une stratégie de plea bargain art. 358 CPP. (D) **Tracing crypto** : pas de mandat Chainalysis CH ni MROS (jugé prématuré sans hypothèse claire sur le wallet de destination). (E) **Communication fils Stefan H.** : courrier formel hebdomadaire d'avancement procédure, sans rencontre personnelle.",
            # Distracteur 2 : spectaculaire médiatique
            " Justification politique : 'donner une visibilité maximale au cas Maria H. pour dissuader les arnaqueurs deepfake et alerter les seniors suisses'. (B) **Communication médiatique** : conférence de presse fedpol-MPC LU vendredi 14h00 (J+9) avec présentation publique : (i) extraits audio anonymisés du deepfake (voix masquée par effet stop-press), (ii) photo de Mme Maria H. (visage flouté, salon EMS reconnaissable), (iii) interview de son fils Stefan H. (Pilatus Aircraft Stans) sur l'effet psychologique. (C) **Compass Security forensique** : mandat express CHF 35'000 (vs CHF 18'000 plan complet) pour rapport en 5 jours (vs 14 jours plan complet) avec présentation publique des artefacts ElevenLabs/Murf détectés (révèle la méthodologie aux attaquants). (D) **L.K. audition** : J+5 avec convocation conférence de presse simultanée, présentation publique 'la mule arrêtée par la police lucernoise' avec photo (sans floutage). (E) **Communication EMS Sankt-Niklausen** : visite de la direction MPC LU et conférence interne aux 89 résidents avec démonstration audio du deepfake (jugée 'pédagogique'), risque trauma collectif assumé pour 'effet préventif'."
        ],
        2: [
            # Distracteur 1 : limité au dossier originel
            " Argumentation détaillée : (a) le dossier Maria H. est en bonne voie de résolution (CHF 4'500 récupérés + L.K. identifiée), ouvrir un démantèlement réseau Telegram nécessiterait des ressources MPC LU disproportionnées par rapport au préjudice individuel ; (b) la coordination NEDIK avec 9 procureurs cantonaux serait politiquement complexe et juridiquement risquée si certains cantons ne soutiennent pas la qualification organisation criminelle ; (c) le tracing crypto Chainalysis sur CHF 7'500 transférés est peu probable d'aboutir vu la sophistication du blanchiment crypto russe. (B) **Pas de démantèlement réseau** : poursuite limitée à L.K. mule + auteur deepfake inconnu, classement art. 310 CPP des autres pistes par 'défaut de qualification organisation criminelle suffisante'. (C) **Pas de coordination NEDIK** : économie de 3-4 mois de coordination inter-cantonale. (D) **MROS crypto** : pas de mandat (jugé inefficace). (E) **OFCS prévention** : pas de campagne nationale (jugée prématurée vu le faible nombre de cas signalés ~12 selon estimations). Communication fils Stefan H. : information mensuelle d'avancement procédure.",
            # Distracteur 2 : expansif non-coordonné
            " Justification politique : 'la Suisse doit montrer fermeté maximale contre les réseaux deepfake russophones'. (B) **Actions cantonales LU autonomes** : MPC LU lance des perquisitions simultanées dans 9 cantons CH (LU + AG + ZG + SZ + UR + NW + OW + ZH + BL) sans coordination NEDIK ni Conseil des procureurs (CPS). Chaque procureur cantonal informé après l'action. Mandat 'flash' fedpol PJF national. (C) **Demande Telegram massive** : commission rogatoire EIMP CH→Saint-Vincent ET Russie ET Émirats Arabes Unis (Dubaï siège opérationnel allégué), demande transmission de tous les canaux russophones d'arnaque aux seniors avec menace de désignation Telegram 'organisation criminelle complice' art. 260ter CP. (D) **Communication médiatique** : conférence de presse MPC LU-fedpol mercredi 11h00 annonçant 'opération Senior-Shield', avec présentation des 89 mules identifiées et des 24 cas de fraude similaires détectés dans 9 cantons. (E) **Coordination internationale** : convocation des ambassadeurs RU et AE par MPC LU directement (sans transit DFAE), demande d'extradition formelle des 12 administrateurs présumés du réseau Telegram (sans dossier solide)."
        ],
        3: [
            # Distracteur 1 : interne LU bref
            " Plan détaillé : rapport interne MPC LU 10 pages, classification 'MPC LU-INTERNAL', diffusion limitée aux 14 procureurs MPC LU + 8 procureurs cantonaux AG + ZG + SZ + UR (cantons CH centrale). Pas de coordination MPC-OFCS-Pro Senectute-FINMA-APEA pour publication conjointe nationale. (A) **Contenu** : (i) chronologie cas Maria H. 15.02-15.08.2024 ; (ii) volumes (CHF 12'000 préjudice initial, CHF 4'500 récupérés, CHF 7'500 perdus, L.K. mule identifiée + condamnée 8 mois sursis, auteur deepfake russophone non extradable) ; (iii) leçons opérationnelles internes MPC LU (méthodologie forensique vocal Compass Security, tracing crypto MROS-Chainalysis) ; (iv) recommandations internes MPC LU pour les 24 cas similaires détectés dans 9 cantons. (B) **Pas de coordination OFCS** pour campagne nationale prévention. (C) **Pas de formation continue HSG ni UniLU ni Pro Senectute**. (D) **Justification doctrinale** : 'éviter de signaler aux réseaux deepfake russophones la méthodologie d'investigation suisse'. Position : la discrétion institutionnelle MPC LU est cohérente avec la tradition cantonale lucernoise. Calendrier : rapport finalisé septembre 2024, communication purement interne.",
            # Distracteur 2 : loi répressive deepfake
            " Plan détaillé : rapport politique au DFJP recommandant nouvelle loi fédérale 'deepfake et protection des seniors' en 5 piliers. (1) **Interdiction législative** : interdiction pénale absolue de la création et diffusion de tout deepfake vocal ou visuel en Suisse, indépendamment du contexte (artistique, satirique, éducatif inclus). Peine privative minimum 12 mois pour création, 24 mois pour diffusion, 36 mois si victime senior > 70 ans. (2) **Obligation de marquage** : tous les contenus audio/vidéo générés par IA doivent porter un watermark cryptographique vérifiable obligatoire (norme OFCS 2024 à créer). Sanction art. 292 CP en cas de défaut de marquage. (3) **Compétence MPC obligatoire** : extension art. 23 CPP à toutes les infractions deepfake (organisation criminelle art. 260ter CP présumée pour création/diffusion en bande). (4) **Mise sous tutelle automatique** : toute personne > 75 ans victime d'arnaque deepfake bénéficie d'une mise sous curatelle administrative automatique APEA art. 393 CC (sans procédure contradictoire). (5) **Surveillance bancaire** : obligation pour toutes les banques CH de bloquer automatiquement tout virement > CHF 1'000 effectué par client > 70 ans, déblocage seulement après confirmation orale par parent désigné. Annonce médiatique de la proposition de loi mercredi 11h00 lors de conférence de presse MPC LU-OFCS-Pro Senectute-FINMA, avant validation politique."
        ]
    }
}

# ── Application ──────────────────────────────────────────────────
total_modified = 0
for scene_id, steps_pads in PADDINGS.items():
    path = Path(f'scenes/{scene_id}.json')
    scene = json.loads(path.read_text(encoding='utf-8'))
    modified = 0
    for step_idx, pads in steps_pads.items():
        step = scene['steps'][step_idx]
        non_ok_indices = [i for i, c in enumerate(step['choices']) if not c.get('ok', False)]
        for pad_idx, choice_idx in enumerate(non_ok_indices):
            if pad_idx < len(pads) and pads[pad_idx] is not None:
                step['choices'][choice_idx]['text'] += pads[pad_idx]
                modified += 1
    path.write_text(json.dumps(scene, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f"  ✓ {scene_id}: {modified} distracteurs étoffés")
    total_modified += modified

print(f"\nTotal: {total_modified} distracteurs étoffés sur 3 scènes")
